### ISSUE TITLE
Maybe change a term in "read more" link of practice 1.3

### ISSUE THREAD

**Issue by leonardovillela** [i0natan/nodebestpractices#130]
Hello Guys.
I'm reading the practices and I'm really enjoying it, congratulations to the work. But I came across an interesting case: "well, there is a framework for that, it's called NPM"

Would not it be more correct and more understandable to use the term tool? "well, there is a tool for that, it's called NPM"

**Comment by leonardovillela** [comment]
If you think it right, I can send the PR.

**Comment by BrunoScheufler** [comment]
You're right! If you want to take care of that, just send a pull request :smile: :+1:

**Comment by leonardovillela** [comment]
Ok, i will send the PR now.

**Comment by BrunoScheufler** [comment]
You can also add your name to the thank you section on the bottom of the main README file if you want to!

**Comment by leonardovillela** [comment]
Ok, I will add and send the PR. Thanks.

**Comment by leonardovillela** [comment]
I open the PR, after review you can close this issue?

**Comment by BrunoScheufler** [comment]
Yes, I'm already at it! Thank you!

**Comment by leonardovillela** [comment]
You're welcome :+1:
