### ISSUE TITLE
Resources for the security best practices section

### ISSUE THREAD

**Issue by BrunoScheufler** [i0natan/nodebestpractices#135]
## Guideline-based resources for web application security
- [Twelve-Factor-App Config](https://12factor.net/config)
- [JWT Blacklisting](https://auth0.com/blog/blacklist-json-web-token-api-keys/)
- [Unsafe RegEx](https://nodejs.org/en/docs/guides/dont-block-the-event-loop/#blocking-the-event-loop-redos)
- [Avoid Eval](http://2ality.com/2014/01/eval.html)

## General web application security resources for Node.js
- [RisingStack Node.js Security Checklist](https://blog.risingstack.com/node-js-security-checklist/)
- [OWASP Web Application Security Checklist](https://www.owasp.org/index.php/Web_Application_Security_Testing_Cheat_Sheet)
- [OWASP Top Ten Project](https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project)
- [@lirantal's Node.js security presentation](https://www.owasp.org/images/f/fa/AppSecIL2016_NodeJS-Security_LiranTal.pdf)
- [Express Official Security Best Practices](http://expressjs.com/en/advanced/best-practice-security.html)
- [Node Security Presentation](https://github.com/w3cj/node-security)

## NPM Packages created to secure Node.js web applications
- [Helmet](https://github.com/helmetjs/helmet)
- [Express Validator](https://github.com/ctavan/express-validator)
- [Express Rate Limit](https://github.com/nfriedly/express-rate-limit)
- [Mongoose](https://github.com/Automattic/mongoose)
- [Sequelize](https://github.com/sequelize/sequelize)
- [Validator.js](https://github.com/chriso/validator.js)

## Miscellaneous resources
- [Node Security Platform (nsp)](https://nodesecurity.io/)
- [Snyk](https://snyk.io/)
- [Sqreen](https://www.sqreen.io/)
- [Node.js VM core module to run code in a sandbox](https://nodejs.org/api/vm.html)

_This list is still in draft stage and to be continuously updated_

**Comment by i0natan** [comment]
another comprehensive work from @BrunoScheufler 

@lirantal let's focus here in the next 1-2-3 days, pick best 5-10 resources so we can have bibliography and inspiration for our content writing

**Comment by i0natan** [comment]
@BrunoScheufler I meant quite the opposite. For efficiency purposes, I would pick 5-7 best sources (3 great blog posts, 1 book, 2 principles site like OWASP). Our goal IMO is to reduce, not to add

**Comment by BrunoScheufler** [comment]
@i0natan this is not what I meant either. However I want to have a good collection of resources we can collect from

**Comment by lirantal** [comment]
Definitely a great list, you're doing wonderful stuff @BrunoScheufler 

Agree with @i0natan about being focused rather than providing too much information where readers tend to "get lost". There are probably enough awesome lists out there for security as well that will cover these (and if not we can create one :-))

**Comment by i0natan** [comment]
@BrunoScheufler I plan going over these resources soon and suggesting which should be on our final list

**Comment by BrunoScheufler** [comment]
@i0natan okay, if you have any suggestions or questions about the list, feel free to share them here!

**Comment by i0natan** [comment]
@BrunoScheufler sorry for the delay, have some milestone soon that doesn't leave much spare time... :(

Pasting some resource I like, I think we should focus on OWASP, Liran's book, and few best practices list:
Great resource about user management mistakes - https://hackernoon.com/your-node-js-authentication-tutorial-is-wrong-f1a3bf831a46
Casual lists:
https://expressjs.com/en/advanced/best-practice-security.html
https://nodewebapps.com/2017/01/03/13-security-best-practices-for-your-web-application/
https://medium.com/@rajapradhan08/best-practices-for-securing-node-js-web-applications-3b69909b2a2a
https://jsblog.insiderattack.net/developing-secure-node-js-applications-a-broad-guide-286afdec69ce

**Comment by BrunoScheufler** [comment]
@i0natan 
> I think we should focus on OWASP, Liran's book, and few best practices list
I think that sounds good, said resources should include the most important points for us to use in a detailed form!

**Comment by i0natan** [comment]
@BrunoScheufler can u plz identify whether those list has any (non-generic, rather node-related) item that we don't

**Comment by BrunoScheufler** [comment]
[This one](https://nodewebapps.com/2017/01/03/13-security-best-practices-for-your-web-application/) seems to contain some generic points matching the content we collected for our general security guidelines checklist. And [this post](https://medium.com/@rajapradhan08/best-practices-for-securing-node-js-web-applications-3b69909b2a2a) contains multiple points we already selected, which might help us although when writing the content.

**Comment by i0natan** [comment]
@BrunoScheufler can you include here a final list with OWASP + Liran's book + 3-5 node.js best practice articles

**Comment by BrunoScheufler** [comment]
@i0natan I'd say the most important OWASP resource might be the [Web Application Security cheat sheet](https://www.owasp.org/index.php/Web_Application_Security_Testing_Cheat_Sheet) in addition to the [RisingStack security checklist](https://blog.risingstack.com/node-js-security-checklist/). Other resources might be the [official express security best practices section](http://expressjs.com/en/advanced/best-practice-security.html).

**Comment by i0natan** [comment]
@BrunoScheufler maybe you can put here a list of the top 5-6 source you found (Liran's book, 4 best practices, OWASP) so anyone who writes bullets like @lirantal @js-kyle can copy quotes easily?

**Comment by BrunoScheufler** [comment]
@i0natan of course! So below are some of the most popular resources:

- [OWASP Web Application Security Cheat Sheet](https://www.owasp.org/index.php/Web_Application_Security_Testing_Cheat_Sheet)
- [RisingStack Node.js Security Checklist](https://blog.risingstack.com/node-js-security-checklist/)
- [Express Security Best Practices ](http://expressjs.com/en/advanced/best-practice-security.html)
- [Liran's awesome book](https://leanpub.com/nodejssecurity)
