### ISSUE TITLE
Dependency caching is a good practice

### ISSUE THREAD

**Issue by samrocketman** [i0natan/nodebestpractices#146]
Probably most appropriate under `Going To Production Practices`.  Dependency caching is using an on premise caching proxy such as Artifactory or Nexus in which to pull NodeJS dependencies for production pipelines.

Real world scenario where this has actually saved my company from halting productivity: [leftpad being unpublished affected many companies where caching would have insulated them from the problem](https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/).

**Comment by i0natan** [comment]
@samrocketman  Welcome! Great idea.

Only having thoughts if today, when unpublish is not allowed anymore and npm-registry is a bit more reliable + yarn + shrinkpack as an alternative, not sure how critical it is. But definitely has a value + better performance for developers/ci/cd

Maybe we should pack into this other benefits of professional artifacts management? what other benefits does nexus/artifactory brign to the table?

**Comment by samrocketman** [comment]
I tend to insulate critical processes from the internet as much as possible.  Artifact repositories have other benefits (depending on your infrastructure) but my best practice recommendation is focused on dependency caching.  Feel free to close this issue if you don't want to include this recommendation.

Dependency caching applies to all where as other benefits a typically good for some and not others.

**Comment by i0natan** [comment]
@samrocketman I just want to discuss and clarify what exactly we recommend. 'Isolate critical process from the internet' is pretty debatable in the age of cloud computing: most of the CI/CD vendors (critical process) are on the internet, the run-time itself is on the internet cloud. 

So it this more about the speed, resiliency (prevent downtime), untrust small vendors (NPM inc < AWS)?

**Comment by i0natan** [comment]
@samrocketman just to clarify - I feel that it's the right thing to do, just need help in distilling the essence of it

**Comment by samrocketman** [comment]
I understand.  After rereading my response it looks a bit terse.  That was not my intent.  I work a lot with running Nexus as a dockerized service so perhaps I could update my code to reflect my existing practices.

ref: https://github.com/samrocketman/nexus3-ssl

**Comment by i0natan** [comment]
@samrocketman I think it's a great idea for a new practice.

I would only restrict in the explanation text that it mostly fits big project that constitutes frequent npm installations in production (scaling-out, rolling version) and repository downtime cannot be tolerable

would you like to write and PR your idea?

**Comment by samrocketman** [comment]
I would like this re-opened.  I forgot about it.  If you can, please assign this to me and I will contribute a PR.

**Comment by samrocketman** [comment]
@i0natan ping for visibility

**Comment by i0natan** [comment]
@samrocketman Great to have you back man.

I'm thinking out loud whether this item is not too niche, npm registry downtime is still rare. Maybe include other reasons to use an artifact manager? what are artifactory/nexus selling points?

**Comment by samrocketman** [comment]
Several years ago my company was unaffected by the unpublished leftpad library.

The goal is simple, to make a delivery pipeline as reliable and repeatable as possible.

In our multi-language projects we proxy dependencies not just for NodeJS but for every language stack being used.

**Comment by i0natan** [comment]
@samrocketman Yes, it's a good practice that might once in a few years prevent deployments block. To my personal judgement, we should keep the guide focused on risks with almost immediate impact. Given this, I suggest to put it as a paragraph within 5.16. (atomic deployments) but not a separate bullet. Does this resonate with you?

**Comment by samrocketman** [comment]
I guess I’m just struggling to relay the value it brings to me.  In practice, `once in a few years` is not my experience.

It’s good to mention it in atomic deployments.  Not all organizations need it.

**Comment by i0natan** [comment]
> In practice, `once in a few years` is not my experience

Did you face a more frequent npm downtimes?
