### ISSUE TITLE
March 2018 maintenance list

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#154]
**Updates**
* Update top badges with Node version and last update date
* Ensure all translations are aligned with the English version

**Flowers**
@ymhtut 
@cwar 

**Stars**
@js-kyle

**Comment by BrunoScheufler** [comment]
@i0natan we might create another issue or list for ensuring the translations are up-to-date because this seems like another type of work compared to the regular chores like adding the flowers/stars and keeping the badges updated.

**Comment by i0natan** [comment]
YUP!

**Comment by BrunoScheufler** [comment]
I think we're done for March 🙂 Closing this now, any updates can be added to the April 2018 maintenance list, which I'll happily cover!
