### ISSUE TITLE
Simplified chinese vs traditional chinese

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#155]
@MattJin 

@idori who's putting the translation links in the home page asks which Chinese did we translate: simplified chinese \ traditional chinese?

**Comment by MattJin** [comment]
@i0natan simplified Chinese.

**Comment by i0natan** [comment]
@MattJin cool, did u see the flags and the credit? is it good enough?

**Comment by MattJin** [comment]
@i0natan  Yes. I think it's wonderful!
