### ISSUE TITLE
Is there interest in the following topics: Refactoring, Architecture or System Design

### ISSUE THREAD

**Issue by TheHollidayInn** [i0natan/nodebestpractices#160]
A few things that come up on projects I have in multiple languages are listed above, but more on them below:

1. Refactoring: I honestly hardly see any of this in the "newer" languages, but there are several books on Java refactoring as well as some on PHP and Python. Here is a good list: https://refactoring.guru. This could fit well in the Code Quality section. There are also good tools like: https://codeclimate.com/ to be used.

2. A few architectures of the top of my head are MV* and Clean/Hex Architecture. Plus adding links to functional and OOP paradigms for NodeJS would be helpful for users to see when and why to use certain choices. The Project Structure section is great, but there is still more to add on as you get larger. 

3. Slightly out of scope, but if you are developing Nodejs, you probably have a few APIs which could use could System Design: https://github.com/donnemartin/system-design-primer

I'd be happy to PR if any of these are of interest.

**Comment by i0natan** [comment]
Welcome aboard! These topics are highly relevant and important and at the same time, 'flamable' and debatable so should get handled with extra care.

The first section (project structure) deals with multiple architecture topics (e.g. microservices, screaming architecture, domain driven design), we definitely can include some wisdom from clean/hex (I personally don't appreciate MV*). For example, bullet 1.2 might include quotes from clean/hex that resonate why express should stay away from the domain

I'll be glad to see some related PR, maybe first before going to the distance share what you intend to add? [Please take into account our content guidelines.](https://github.com/i0natan/nodebestpractices/blob/master/writing-guidelines.md)

**Comment by i0natan** [comment]
@TheHollidayInn any follow-up thoughts from your part?

**Comment by TheHollidayInn** [comment]
Sorry for the delay! 

Reading over the first section again, it does seem to include the principals of good architecture without explicitly choosing. I'm going to cross reference my material to see if there is more I can add.

I would like to add bullet to section 4 with a summary of creating a plan to refactor and use a tool like CodeClimate as a starting guide. Would that be okay?

Maybe in section 1, 5 or 7 I could add a bullet about offload longer tasks to redis. I can find some examples/docs. From reading your guidelines I do see this `Each advice should be related directly to Node.js and not to software development in general` so I am trying to think about Nodejs specifics, but the System Design items might be more general and not fit in. Although it would be good if you develop APIs/Microservice systems to at least have a reference to the ideas.

**Comment by i0natan** [comment]
@TheHollidayInn sorry for the delay, liked very much few of your ideas

Short intro - Everything, after all, is related to 'general sw development'. The main idea here is to write about topics where the nodejs interpretation/implementation are non-trivial with emphasize on the node related topics. The specific tools (e.g. redis, code climate) should not be the main topic rather the concept and the leading tools can be specified in the end

I find it a great idea (!) to write about static code analysis as part of the CI with emphasis on js/node related issues like avoiding over nested closures that increases the measured code complexit or any other interpretation of complexity analysis and node. Anyway, the tools (plato, code climate, sonarcube) shold be kept to last

Separating long-running, non customer facing, to external workers might also deserve a bullet but the implementation is highly controversial - I can think of 7 different techniques to achieve that. What for example can we write under this bullet?

**Comment by i0natan** [comment]
Closing -> Moved to a PR
