### ISSUE TITLE
April maintenance list

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#172]
Assignee: @i0natan

**Updates**
* Update top badges with Node version and last update date
* Ensure all translations are aligned with the English version

**Flowers**
@keyfoxth
@utkarshbhatt12 

**Stars**

**Comment by sagirk** [comment]
It seems we're behind on the April maintenance list.

Also, have we not opened a May maintenance list yet?

@i0natan @idori @refack @BrunoScheufler I'd like to help out, if that's okay.

**Comment by sagirk** [comment]
Update: Filed an issue for [May 2018 maintenance](https://github.com/i0natan/nodebestpractices/issues/183).

**Comment by BrunoScheufler** [comment]
@sagirk yeah you're right, if you're up to adding the flowers for this list and create a PR, that would be helpful!

**Comment by i0natan** [comment]
@sagirk Your help is much appreciated

**Comment by sagirk** [comment]
Opened a [PR](https://github.com/i0natan/nodebestpractices/pull/185).

@i0natan @BrunoScheufler 
Taken care of everything for April except this bit:
* Ensure all translations are aligned with the English version

What are the steps to ensure above?

**Comment by BrunoScheufler** [comment]
This is rather complicated due to the need of staying in contact with the translation groups, don't worry, we'll happily take care of that. Great job however!

**Comment by i0natan** [comment]
@sagirk If you're up to additional improvements, we've bunch of improvement ideas in our bag waiting for someone to push them forward

**Comment by BrunoScheufler** [comment]
@i0natan do we? 😅

**Comment by i0natan** [comment]
:)

Yeah:
1. Bibliography project - extracting all the sources we used into one list on the home page including books, bloggers, etc.
2. For each bullet, show list of top vendors with a comparison of the key metrics (e.g. monitoring solutions)
3. Others

I didn't ask from you to look into one of this because you seem busy but should you have time I'd be glad if you can handle some additional project

**Comment by BrunoScheufler** [comment]
Oh no worries 😄 I'll message you if I have the demand for these tasks!

**Comment by sagirk** [comment]
@i0natan I can start with the Bibliography project. Where can I learn more? Any existing issue/repo/example?

Just to be clear, this is different from the planned [credit section](https://github.com/i0natan/nodebestpractices/issues/90), right?

**Comment by i0natan** [comment]
@sagirk Thanks, this could be an amazing contribution. This includes the credits section but also other more strategic activities and goals.  I'll share full-details, thoughts and steps by tomorrow morning. To be clear, it doesn't mean that you have to handle all work alone, rather you lead

**Comment by i0natan** [comment]
@sagirk @BrunoScheufler See the project I just added here: https://github.com/i0natan/nodebestpractices/projects

Read the bibliography project description. The aim is to enrich our content, but prioritize it by popular and important sources.

Let me know what you think.

**Comment by i0natan** [comment]
@sagirk Is this something you'd like to lead (with our support and working hands of course)?

**Comment by i0natan** [comment]
@sagirk I see your point, we can start small and expand this as we go.

For example:
Step 1- create a simple bibliography list on the home page, and put there all the sources we used. We have a data entry guy who can help with the extraction work (getting the URLs of all blogs from all the bullets), he can give you a plain list of author-url-title and you just place it within the bibliography

Step 2 (optional) - detect influencers, there are tools who can do that in 20min, then scan their blogs/books for additional quotes/examples. Or even ask from them, they'll love to appear in this list. I can do the first part of influencers detection

What do you think?

**Comment by sagirk** [comment]
Sounds good.

A couple of follow-up questions:
1. How do I get in touch with the data entry guy?
P.S.: Its been a fortnight since our last conversation, so if the extracted list is ready already, I can get started.

2. Yes, having you do the influencers detection would be helpful. I can get in touch with them and check if they would want to appear on the list.

**Comment by i0natan** [comment]
@sagirk Cool

1. I'll do this on Monday and it will be probably ready by Tuesday
2. Cool, let's open a dedicated issue to chat about this?
