### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by FedericoBiccheddu** [i0natan/nodebestpractices#173]
I can help to translate this repo in italian 😃

**Comment by i0natan** [comment]
Hey @FedericoBiccheddu , welcome aboard!

Will be honored if you can lead this transation. You're the lead! I'll be at your disposal should you need anything. Please create a branch for this work and PR to master once it's 100% done.

I would ask/recommend only 2 important guidelines:

Keep the same content & formatting - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and them translate
Duplicate pages - the content should be translated over a page duplication. Readme.MD became Readme.italian.MD, all other files should be duplicated similarly. So the number of English & Italian pages should be the same. Will create a bold link from the English home page to the Italian home page (with bold credit of course...).

Your name will be on the top of the Italian page.

What do you think?

**Comment by FedericoBiccheddu** [comment]
Sounds perfect.

I have already started working on it 😄

**Comment by i0natan** [comment]
@FedericoBiccheddu anxious to see the results :)

**Comment by matteocrippa** [comment]
I see this is pretty stuck, started working on a new fork

https://github.com/matteocrippa/nodebestpractices/tree/feature/italian

**Comment by i0natan** [comment]
@matteocrippa Welcome aboard ✋ 🌷 

I'll be glad to help in anything I could, maybe ask @FedericoBiccheddu if he can actively working on this or maybe has some artifcats to share?

**Comment by fedemengo** [comment]
Hello, me and @mrcolo would like to help with the italian translation, we could pick up where @FedericoBiccheddu and @matteocrippa left off

**Comment by i0natan** [comment]
> Should we open a new issue?

It could be awesome if you could bring this work-stream to completeness!

I don't see a reason to open a new issue, you use this one to update on progress, share your working branch name, we can also Tweet about this and ask on the home page top panel whether there are other Italian contributors who are willing to take part.

Is there anything else we could help with?

**Comment by fedemengo** [comment]
We have another contributors for the italian translation @andreaziani.
We will be working on the following branch https://github.com/fedemengo/nodebestpractices/tree/italian-translation

**Comment by i0natan** [comment]
@js-kyle Can you kindly be in charge here (going by the operations-manual languages)?

p.s. engaging now with Italian & Egypt translation
