### ISSUE TITLE
May 2018 Maintenance

### ISSUE THREAD

**Issue by sagirk** [i0natan/nodebestpractices#183]
Assignee: @BrunoScheufler

**Updates**

* Update top badges with best practices item count, last update date and Node.js version
* Ensure all translations are aligned with the English version

**Flowers**
@duartemendes
@js-kyle
@sagirk
@serv 

**Stars**

**Core Team**
@js-kyle

**Comment by BrunoScheufler** [comment]
👍

**Comment by i0natan** [comment]
Performed the May maintenance checklist

@duartemendes @js-kyle @sagirk @serv - You were assigned flowers for the great contrubition. Hope to work together on other improvements

@js-kyle Can you kindly add yourself to the core team as you have to include a BIO about yourself?
