### ISSUE TITLE
Limit login attempts

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#186]
@lirantal @js-kyle @BrunoScheufler Should we add this (login attempts limit) to our security list: it's a very common brute-force technique and addressing that requires understanding of Node tools (probably a middleware that uses some redis-like cache with sliding expiration)?

**Comment by BrunoScheufler** [comment]
@i0natan I think that's actually a good idea. I'd go for some sort of cooldown after a set number of failed login attempts, but I'm not sure whether to apply that to an ip address or somewhat more specific which would be better IMO.

**Comment by i0natan** [comment]
More specific - Username. IP restirction is already covered on the LB rate limiting.

This package seems great:
https://www.npmjs.com/package/express-brute

**Comment by lirantal** [comment]
In my book I cover this one: https://www.npmjs.com/package/limiter

**Comment by i0natan** [comment]
@lirantal I think it worth a bullet, what do you think?

The express-brute supports redis, couldn't see support for out-of-process cache on the later

**Comment by LeoLoupos** [comment]
Do you mean something like that?

```
var RateLimit = require('express-rate-limit');
var RedisStore = require('rate-limit-redis');

//Prevent Brute Forcing with Rate Limiting
try{
    var limiter = new RateLimit({
        store: new RedisStore({
            expiry: 60,
            prefix: 'app_main_server',
            client: require('redis').createClient()
        }),
        max: 100, // limit each IP to 100 requests per windowMs
        delayMs: 0 // disable delaying - full speed until the max limit is reached
    });
} catch (e) {
    console.error(e);
}

 
module.exports = {
    limiter
}
```

**Comment by i0natan** [comment]
Or using express-brute:

`var ExpressBrute = require('express-brute'),
	RedisStore = require('express-brute-redis');

var store = new RedisStore({
	host: '127.0.0.1',
	port: 6379
});
var bruteforce = new ExpressBrute(store);

app.post('/auth',
	bruteforce.prevent, // error 403 if we hit this route too often
	function (req, res, next) {
		res.send('Success!');
	}
);`

**Comment by LeoLoupos** [comment]
Thanks @i0natan , thats a very nice approach .

On the other hand , if we want a more globalized approach.

with the [Maxmind GeoLite2 database](https://dev.maxmind.com/geoip/geoip2/geolite2/) and [node-maxmind-db](https://github.com/PaddeK/node-maxmind-db)  for the IP geolocation portion.

```
var express = require('express');
var RateLimit = require('ratelimit.js').RateLimit;
var ExpressMiddleware = require('ratelimit.js').ExpressMiddleware;
var redis = require('redis');
var app = express();

//Default
var defRateLimiter = new RateLimit(redis.createClient(), [{interval: 1, limit: 10}], 'default_rate_limit');

var defMiddleware = new ExpressMiddleware(defRateLimiter);

//Uk
var ukRateLimiter = new RateLimit(redis.createClient(), [{interval: 1, limit: 20}], 'uk_rate_limit');

var ukMiddleware = new ExpressMiddleware(ukRateLimiter);

var rateLimitResponder = function(req, res, next) {
  res.status(429).json({message: 'Rate limit exceeded.'});
};

var geoLimiters = {
  default: defMiddleware.middleware(rateLimitResponder),
  uk: ukMiddleware.middleware(rateLimitResponder);
};

var limitFn = function(req, res, next) {
  var reqIsoCode = getIsoCode(req);
  var limiterMiddleware = geoLimiters[reqIsoCode] || geoLimiter.default;
  limiterMiddleware(req, res, next);
}; 

app.get('/', limitFn, function(req, res, next) {
  // request is not rate limited
  ...
});

```
The key is that you must differentiate the two rate limiters by using a custom prefix (see the RateLimit constructors). The way the IP addresses (or other request identifier you specify) won’t conflict.

**Comment by i0natan** [comment]
@LeoLoupos That looks interesting, can you elaborate why create two limiters or why create one per region? what is "ratelimit.js"?

**Comment by LeoLoupos** [comment]
Ratelimit.js : https://github.com/dudleycarr/ratelimit.js/blob/master/README.md

By the time you have an international server, it is good to apply rate limiting practices for specific regions. Because ,if you can have more powerful machines , on for e.x UK rather than Slovenia, it is the only way to configure different limits.

**Comment by js-kyle** [comment]
Closing, this bullet was included in the security release
