### ISSUE TITLE
Suggestion 5.7. maintenance endpoint is dangerous when it becomes a target of DDOS

### ISSUE THREAD

**Issue by serv** [i0natan/nodebestpractices#187]
Opening up an endpoint that generates MBs of Node dumps can be dangerous.
Once the endpoint is exposed, anyone can write a simple script that repeatedly hits on the endpoint and bring down the app server.
If this endpoint is exposed only for signed-in admin users, then this risk can be mitigated. You should mention this as a hard requirement for this suggestion.

**Comment by i0natan** [comment]
@serv Welcome!

It's written that "A maintenance endpoint is a plain secured HTTP API" - maybe we should emphasize that his endpoint must be highly secured and besides typical authentication be opened to white-listed IPs only

Do you wanna PR something like this?

**Comment by serv** [comment]
I'll mention that this should be an endpoint that is not available to public. And if someone who is not authorized attempts to request the endpoint, they get 403.

I think white-listed IPs are too stringent of a requirement. People might be debugging from places (at home, cafe etc) that might not be whitelisted. Also at work network, they might have variable IPs for users.
