### ISSUE TITLE
Using named parameters in functions

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [i0natan/nodebestpractices#193]
Inspired by this [awesome article](https://medium.freecodecamp.org/elegant-patterns-in-modern-javascript-roro-be01e7669cbd)
I've found it super useful to use named parameters when using functions instead of unnamed parameters.

The benefits are:
1- Order of parameters doesn't matter.
2- Default parameters.
3- Anyone who reads the code knows what this parameter is instantly.

```js
// use named parameters
const add = ({ x, y }) => x + y;

let sum = add({ x: 4, y: 5 });


// avoid
const add = (x, y) => x + y;

let sum = add(4, 5);
```

**Comment by i0natan** [comment]
@AbdelrahmanHafez Welcome! Interesting idea for a best practice. 

I don't know if it isn't too subjective as it pollutes the code with overhead that theoretically could be augmented by the IDE (see below), maybe advice a clear strategy on parameter names + optionally use named parameters?

I'm not sure if this isn't the IDE/tooling job to show the param name for the caller of the function. For example, webstorm prepend the param name to the param value, see prtscn here:
https://www.jetbrains.com/help/phpstorm/viewing-method-parameter-information.html

**Comment by AbdelrahmanHafez** [comment]
How we name our parameters isn't the point here, we should have a section on naming variables in general if we don't already have one, but that's not what this is about.

I haven't done enough research on how IDEs show the parameter names, however, I use VSCode, and it is not consistent as it should be, specially if you require your functions using 
```js
require(path.resolve('./path/from/root'));
```


Also, it's not just about writing the code, it helps more in the process of reading the code and understanding it. Take the 2 following functions for example:

```js
findUsersByRole('admin', true, false);
```

```js
findUsersByRole({ role: 'admin', withContactInfo: true, includeInactive: false });
```

Which one reads better?

**Comment by i0natan** [comment]
The second. But the same value can be provided by some IDEs (see the image, it looks exactly like your second example without changing anything in the code...), other IDEs will follow soon. Making all app functions receive object is not a very trivial and highly-standard. Consequently, I find it to be a good idea but not sure if compelling enough to be a  "best practice"

**Comment by AbdelrahmanHafez** [comment]
VSCode can't get some functions if they're hooked in the global object somewhere in the project, in order to get these functions parameters, it'll have to loop through all the project's files. There are functions where it simply can't know what this function is on the time of writing/reading, these functions are assigned somewhat dynamically.

I agree though, it may not be a "best" practice, however, let's leave the issue open for a while and see what others think.

**Comment by i0natan** [comment]
Sounds like a good idea, you may link to this issue from some groups or ask at reddit + we can also create a Twitter Poll

**Comment by AbdelrahmanHafez** [comment]
Sure, a Twitter poll sounds like a good idea.
I'll post on Reddit as well.

**Comment by i0natan** [comment]
@AbdelrahmanHafez  https://twitter.com/nodepractices/status/1012413507667718146

**Comment by lhorie** [comment]
Not a good addition IMHO. Here are a few (of numerous) examples that get awkward:

```
getConfig({config: 'foo.bar.baz'}) // yo dawg I heard you like config
// vs
getConfig('foo.bar.baz')

const fnWithOptionalArgs = ({arg = 'default', another = 'default'} = {arg: 'default', another: 'default'}) => {}
// vs
const fnWithOptionalArgs = (arg = 'default', another = 'default') => {}

const variadicArgs = ({args = []} => {args: []}) => {}
// vs
const variadicArgs = (...args) => {}

const withName = ({item}) => item.name
users.map(user => withName({item: user}))
// vs
const withName = item => item.name
users.map(withName)
```

The "best practice" is to use named params when they make sense. But the whole point of a best practice is that you can generally follow a best practice blindly without understanding the reasoning and intricacies behind them, but even then there's a high chance you're doing the right thing.

Validating named parameters correctly takes discipline and if done poorly can lead to more bugs than if you just used inline params.

**Comment by AbdelrahmanHafez** [comment]
I agree, it's not a good pattern when a function takes only one parameter and returns only one thing, so there's no point in naming the parameters, like the getConfig, and withName example.

However, for the other examples, you don't need to repeat the parameters again, you can simply set the default to an empty object like so:
```js
const fnWithOptionalArgs = ({arg = 'default', another = 'default'} = {}) => {}
// vs
const fnWithOptionalArgs = (arg = 'default', another = 'default') => {}
```

There's probably a typo in the variadicArgs example, I am not sure what you're trying to achieve with such a function, but I assume it can be done with the following as well
```js
const variadicArgs = ({...args}={}) => {}
// vs
const variadicArgs = (...args) => {}

// a use case where I have actually used it yesterday was
const doStuffToOrder = async ({ _id, ...query }, { status, otherField }) => {
  // do this to order anyway
  await Order.updateOne({ _id }, { status });

  // update order only if it fits the rest of the criteria
  await Order.updateOne({ _id, ...query }, { otherField });
};
```

**Comment by AbdelrahmanHafez** [comment]
You got a point there, it's not a best practice that should be followed blindly without knowing the possible downsides.
