### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by SandroMiguel** [i0natan/nodebestpractices#196]
Can I help with portuguese (Portugal) translation?

**Comment by i0natan** [comment]
@SandroMiguel Welcome aboard! It can be amazing to have a Portuguese version

I'm sharing here instructions how usually we kick-off a translation, is this descriptive enough? do you want to take it alone or join others?

Open a branch - each translation is done on a dedicated branch that is PRed to master upon completion

Duplicate pages - the content should be translated over a page duplication. Readme.MD became Readme.port.MD, all other files should be duplicated similarly. So the number of English & Portuguese pages should be the same. Will create a bold link from the English home page to the Portuguese home page (with your name on top of it...).

Keep the same content & formatting - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and them translate

Your name will be on the top of the Portuguese page.

What do you think?

**Comment by SandroMiguel** [comment]
Great! I can do this myself, but if someone wants to help, it's better and faster.
Page duplication: I can create the Readme.port.MD but what do you think about README.pt-PT.md? It's more explicit with ISO 639-1 + ISO 3166-1-alpha-2. In future we can have README.pt-BR.md to Portuguese-Brazil translation.

**Comment by i0natan** [comment]
Sounds like the right way to do it. Someone can help in copying all the pages, but as for the translation itself we have to seek Portugese speakers, I can ask on Twitter + open issue @SandroMiguel

**Comment by SandroMiguel** [comment]
Hi @i0natan, I already started the translation for README.pt-PT.md
What do you think about create a PR for each .md file individually? Some translated content it's better  than nothing, like [MDN](https://developer.mozilla.org/pt-PT/docs/Web/JavaScript/Reference/Global_Objects/Array/includes).
Let me know about your tweet so I can retweet it.

**Comment by i0natan** [comment]
In terms of UX, we don't have languages links per bullet rather per the whole repo, so when a visitor opts to read the Portugese version he will be disappointed if 90% is in English. If we continue with this model, we should translate at least the home page.

Maybe we should consider creating translation links per item than it will be easier for people to transalate shorter items? @idori what do you think?

Follow the nodepractices twitter, I'll tweet today. Are there any Node Portguese FB groups to ask in?

@SandroMiguel

**Comment by SandroMiguel** [comment]
I think it's more confusing to create translation links per item.

**Comment by i0natan** [comment]
@SandroMiguel Than does it resonate with you that at least the home page should be translated?

**Comment by i0natan** [comment]
@SandroMiguel Than does it resonate with you that at least the home page should be translated?

**Comment by herodrigues** [comment]
@SandroMiguel  @i0natan I'm Brazilian and I can help with the pt-BR translation. It'll be easier to translate from the pt-PT translation.

**Comment by SandroMiguel** [comment]
Hello @herodrigues, you can start translate from here https://github.com/SandroMiguel/nodebestpractices/blob/master/README.pt-PT.md
Already translated up to 2.1

**Comment by i0natan** [comment]
@SandroMiguel @herodrigues  Cool, let me know if I can help with anything

**Comment by SandroMiguel** [comment]
Hi @i0natan, should I put the Portuguese flag in "Translations in progress". I'm still translating this repository myself.

**Comment by i0natan** [comment]
@SandroMiguel Is the majority of the 1st page translated or at least the upper part? if so, sounds like a great idea

**Comment by SandroMiguel** [comment]
Hi @i0natan, I've added the Portuguese flag in the translations in progress section. 
PR -> https://github.com/i0natan/nodebestpractices/pull/242

**Comment by i0natan** [comment]
@sagirk Assigned to you so you can experiment a translation issue once. If your plate is full, feel free to bounce back to me

**Comment by sagirk** [comment]
@i0natan Sure, thanks! It'll be a good issue to cut my maintainer teeth on. 💯
