### ISSUE TITLE
APM can't send metrics if the process was killed

### ISSUE THREAD

**Issue by ghost** [i0natan/nodebestpractices#197]
According to this this [rule](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/shuttingtheprocess.md), we should shut down the process whenever an untrusted error happens. At the same time we should have an APM set up as described [here](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/apmproducts.md).

The problem is that oftenly APM process are set up at the very beginning of the first file to keep track of the whole application. They run as a "background process" collecting and sending data to an APM server.

If you kill your process whenever an untrusted error happens, that means this error would likely be not tracked. So I wonder if we should really kill the process and take the risk of not tracking the error?

**Comment by i0natan** [comment]
@chicocode Welcome. 

APM should not be the first line of defense and it doesn't replace traditional error handling and monitoring. So in case of an error that might, or not, lead to process exit, the error should be caught by the catcher (e.g. express middleware error handling) or by the unhandled rejection/exception and get logged to the reliable source that is being aggregated and monitored.

APM serves as the fancier level of discovering hidden/tricky issues. That said, most APM can catch all type of errors as they instrument the code + have a local agent that guards the process but I wouldn't build my error strategy on expensive 3rd products.

Does this make sense?

**Comment by chicocode** [comment]
Thanks @i0natan !

Yes, that makes sense, and I also agree we shouldn't rely on 3rd party services.
But even if we log these error to a reliable source, the process of logging is usually asynchronous done, right?
If so, that could also lead to an unlogged error?
Unless we really make sure the error was sent to the source, but I've never heard of a logging library that has an api like that.

**Comment by chicocode** [comment]
Hey, sorry for being so late!
What I understood from this [rule](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/shuttingtheprocess.md) is that the application is responsible for exiting the process with an error exit code (greater than 0), thus no one will kill the process externally, right?
```js
process.exit(1)
```

Regardless of who kills the process, there is a very important information attached to every exception: the source. If I can find the source of an exception easily I can also fix an eventual production bug faster, no?

**Comment by i0natan** [comment]
@chicocode The app can *try to exit with the desired code and capture a descriptive Error with the source. In most cases, this is doable, valuable and how to achieve this is described in greater details on the error handling section.

Sometimes the app is being killed from an external source. For example, where your cloud platform decided to scale-in or restart servers, in that case, there is no code exception and there's nothing you can fix in your code. Code-wise, there is no source. The failure is originated in the ops side and can be found in non-applicative logs

Does this address your concern?
