### ISSUE TITLE
What's the best way to handle adding modules/plugins/extensions/etc?

### ISSUE THREAD

**Issue by mishaor** [i0natan/nodebestpractices#202]
Let's assume that I use a project that serves: 
```html
<html>
    <body>
        Hello World! 
     </body>
</html>
``` 
over HTTP.
I want to add a `<!DOCTYPE html>` and a title.
There's two plugins (`helloworld-doctype` and `helloworld-title`) and a custom made initialization file:
```js
const helloworld = require('helloworld');

var server = new helloworld({
    modules: [
        'helloworld-doctype',
        'helloworld-title'
    ]
});

server.serve(80);
```
So, let's assume that I'm a Node.js developer.
I want to implement this functionality in my Node.js project.
What's the best way to do that?

**Comment by i0natan** [comment]
You want to render this on the server or on the frontend? any reason not to use robust, mature and popular 'rendering' frameworks like Angular/React/Vue (all support also server side rendering)? Or is this more of a general question on extensibility?

**Comment by mishaor** [comment]
@i0natan it's a more general question on extensibility

**Comment by mishaor** [comment]
somewhere around 4-5 months and no response

**Comment by BrunoScheufler** [comment]
@mishaor I can't speak on behalf of @i0natan but I guess he's lost track of all the issues, so I don't think this was on purpose.

As to your issue, I guess you could also simply read the file and prepend/append your wanted context and serve it afterwards, but I'd agree to @i0natan, choosing a templating solution like handlebars or a real framework might make it even more easy for you.

**Just as a quick note**, this project is all around concepts regarding Node.js application design, we're less focused on solutions to implementation problems (excluding some cases), so maybe there's a better place you could refer to with your question.

**Comment by i0natan** [comment]
@mishaor First, apologies! This just slipped through the cracks, I wish you had reminded me before 😞 

Thoughts - at the simplistic level you can have many modules, each represented by a single file that exports a 'render' method. Your orchestrator/renderer class should loop through the modules and call the render method. The modules themselves are better not just return coded HTML rather use some templating engine partials like [handlebars-partials](https://mandrill.zendesk.com/hc/en-us/articles/205582537-Using-Handlebars-for-Dynamic-Content)

If applicable, better render on the frontend end using a specializing framework - each module might return a React (Vue/NG/whatever) component package URL, and your React app can read from API/CDN all the components [and dynamically render them](https://www.slightedgecoder.com/2018/10/28/loading-react-components-dynamically-on-demand-using-react-lazy/).

Is this a step toward the right direction?
