### ISSUE TITLE
*Vote here: how should our example solution look like?

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#204]
We want to start demonstrating all the best practices in a code solution. Should it be a minimal boilerplate/starter for new projects or rich example application? 

Help us decide here:

https://twitter.com/nodepractices/status/1014851478580875265

@refack @idori @js-kyle @BrunoScheufler @lirantal @benjamingr @kevinrambaud @t1st3 @kudapara @kalitas @matheusrocha89 @ChangJoo-Park @mfine15 @squgeim

**Comment by MarkAdell** [comment]
What is the state of this?

**Comment by i0natan** [comment]
@MarkAdell Still considering whether this is the right place to spend so many nights during the next year? :]

What do you think? would you use it as a starter or for learning? any other thoughts/recommendations will be great

**Comment by i0natan** [comment]
@MarkAdell Curious to hear, which are your favorites boilerplates?

p.s. had a look at your starter, looks very nice. Consider not putting DB logic in an "api" as they server different purposes and layers

**Comment by MarkAdell** [comment]
@i0natan Thank you!

What do you think of putting the dataAccess files under a folder named "DAL" inside src/db folder?

these are some of my favorites boilerplates :
https://github.com/cham11ng/typescript-api-starter
https://github.com/danielfsousa/express-rest-es2017-boilerplate
https://github.com/EQuimper/nodejs-api-boilerplate
