### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by edvinkuric** [i0natan/nodebestpractices#205]
Hey guys,

i just stumbled upon this repo by looking at some github-issues for mongoose - awesome 👍 

i would love to contribute to this repository by creating a german translation.

Should i start by creating the branch "german-translation"?

Best regards, 
Edvin

**Comment by i0natan** [comment]
@edvinkuric Welcome aboard!

@BrunoScheufler, this must be your ticket, right? :]

**Comment by BrunoScheufler** [comment]
@i0natan obviously! :smile: 

@edvinkuric happy to help out if there's anything!

**Comment by i0natan** [comment]
@BrunoScheufler You may copy instructions from #196
