### ISSUE TITLE
Is `new Function` insecured?

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#211]
@lirantal @js-kyle @BrunoScheufler As I go over the security content before we publish, I found this statement in bullet 6.15: "Another language feature that should be avoided is `new Function` constructor"

Is it so? I wasn't aware of that and would like to ensure that it means what it means

**Comment by lirantal** [comment]
Yep, that's indeed the case.
These all belong in the same family of evil: `new Function`, `setTimeout()`, `setInterval()` for the reason that they all accept strings as input which is then interpreted and executed.

I'm covering that in my book for further explanation but I believe that's already straight-forward.
