### ISSUE TITLE
Uncaught exceptions as a security weakness

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#212]
@lirantal Sharing an idea for the security list - one of the most practical ways,IMO, to render a Node process irresponsive is by generating uncaught exceptions/rejections and letting the process crash (many just don't handle these events or handle improperly). If you agree, than catching+handling+monitoring+alerting on these events is a mandatory security protection measure. What do you think?

**Comment by lirantal** [comment]
I would say that it is a good measure to generally restart the process if you're in an undefined state where an exception wasn't caught.

**Comment by i0natan** [comment]
Yes, my point being is that many indeed do only that (no critical alerting on process crash), then typically some input leads to a process crash. If an attacker could identify that input - he could easily generate denial of service with infinite restarts. This a weakness that is unique to Node.js @lirantal
