### ISSUE TITLE
Use gitbook or hexo style of documentation.

### ISSUE THREAD

**Issue by kudapara** [i0natan/nodebestpractices#22]
I was thinking that if someone with experience in using [gitbook](https://www.gitbook.com/) or[ hexo](https://hexo.io/) could make a version of this repository and use github pages to host it then it would be easier to navigate and read the guide.

### Example with gitbook
 * [redux documentation](http://redux.js.org)

### Example with hexo
 * [vuejs documentation](http://vuejs.org)

**Comment by i0natan** [comment]
@kudapara interesting opportunity, does gitbook/hexo support PR?

**Comment by i0natan** [comment]
@kudapara any chance you kindly check whether it allows collaborative editing so the community can PR changes? any idea about the required effort to migrate all the info we have?

+ thanks again :)

**Comment by kudapara** [comment]
I suppose it does support PR. I might have to do some research and work on the feature if someone with the experience doesn't.

**Comment by kudapara** [comment]
Both ***gitbook*** and ***hexo*** support markdown which is the format this repository is currently using so collaboration is going to be easy.

But I think we could go with ***hexo*** as it is free and open source whereas ***gitbook*** only allows 5 collaborators on its free tier.

**Comment by i0natan** [comment]
@kudapara great idea. I'm not familiar with both so plz allow few days to experience how hexo feels like and will get back to you soon @idori

**Comment by kudapara** [comment]
Awesome :fire: @i0natan @idori

**Comment by idori** [comment]
hey @kudapara, thanks for the input! Had a busy week but I'll go over Gitbook and Hexo as soon as possible and update on progress

**Comment by i0natan** [comment]
@idori maybe @kudapara can exemplify how one section look like using Hexo

**Comment by kudapara** [comment]
@idori and @i0natan let me make a prototype

**Comment by idori** [comment]
@kudapara sure, thanks for contributing!

**Comment by kudapara** [comment]
You can have a look at this draft I made https://kudapara.github.io/nodepractices. Its still work in progress but it should give you an idea of how this site could be like. @i0natan @idori

**Comment by i0natan** [comment]
@kudapara Ido will probably take a look soon. Thanks again.

Side question - r u interested in being part of our core team and help manage this project?

**Comment by kudapara** [comment]
Sure I am interested. :smile:

**Comment by i0natan** [comment]
cool :)

can u drop me an email to 'me' //at// 'goldbergyoni' .com?

**Comment by i0natan** [comment]
@idori @kudapara to me it doesn't seems like it allows PR and collaborative editing like 'code', am I correct?
