### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by gsipos** [i0natan/nodebestpractices#221]
Consider adding TypeScript as a recommendation. It improves code quality/maintainability, catches bugs, so it has a place in this list imho.

**Comment by i0natan** [comment]
@gsipos  Just created a poll: https://twitter.com/nodepractices/status/1033071141932425217

**Comment by i0natan** [comment]
Surprisingly, 40% think that TS is a consensus best practice, probably many of our existing bullets won't get so many upvotes...

We may rephrase it in a way that will be probably agreed by most - "Add some level of type safety - TypeScript, flow or vanila ES with explicit schemas (e.g. JSON schema)".

**Comment by BrunoScheufler** [comment]
@i0natan I thought I added a comment here stating your exacts thoughts: I believe it's a good idea to let everybody choose his favorite when it comes to this topic, be it TypeScript, Flow or whatever else, as a long as it has some guarantees for type-safety through tooling, which JavaScript obviously lacks, hence we're having this discussion. Maybe we can unify these with a point 👍
