### ISSUE TITLE
Extending testing best practices

### ISSUE THREAD

**Issue by antoniq** [i0natan/nodebestpractices#222]
Hi there,

Together with @janis91 we have been working on a detailed overview of Node.js Testing best practices. We have published them in a blogpost [https://blog.novatec-gmbh.de/modern-microservice-testing-concept-real-world-example/](url) and we provide a showcase project in github [https://github.com/nt-ca-aqe/blog-microservices-testing-nodejs-typescript](url). Would that be interesting for you? I think especially for integration/component testing and contract testing, one does not find many examples. 

Let us know!

Cheers,
Antoniya

**Comment by i0natan** [comment]
@antoniq @janis91

Welcome.

This is very interesting. And very important. I added your post to my learning queue and will read soon. There are also some other important JS testing type that are not covered, also have some post waiting for finalization for many time (e.g. property based testing, chaos testing, etc)

Would you be able to format some of the content as bullets in our testing section?

**Comment by antoniq** [comment]
Hi @i0natan ,

Sure, let us know once you have read the blogpost content. We have followed the testing types defined in the modern Agile Testing Pyramid.   

Cheers,
Antoniya

**Comment by i0natan** [comment]
@antoniq, sure thing, plan to do it over the weekend

**Comment by antoniq** [comment]
Hi @i0natan ,

Thank you for taking your time to have a look! We will try to answer your questions:
1. As explained in the blogpost, it is recommened doing both. Integration testing focuses on the interaction with only one external component. Furthermore, scenario selection plays a key role - one does not need to test everything once again in the component test. 
2. Regarding naming - it depends on the test target group. In our example, it is closer to the technical level. In case of target for people that are closer to the business - a tool like Cucumber can be integrated on top that will provide better readibility. 
3.  See 1.
4. Sinon is used for the unit tests, Nock was researched as a service simulator alternative. As mentioned, we did not find tool that fits our project needs. 
5. It is this tool: https://sketch.io/sketchpad/ 

Regarding collaboration - your suggestion sounds very interesting. 
Currently, we cannot say however how much time we can invest and when. Feel free to start. It could be that in 2-3 month we have more time to collaborate on the practices.

Cheers,
Antoniya and Janis

**Comment by i0natan** [comment]
@antoniq 

> "Integration testing focuses on the interaction with only one external component. Furthermore, scenario selection plays a key role - one does not need to test everything once again in the component test"

Can you provide a concurrent and real-world example where this might worth the effort?

**Comment by antoniq** [comment]
Hi @i0natan ,

I am back from vacation and have time now to look at your question. I am not sure that I get your question completely - is it about the diff between integration and component testing?

**Comment by i0natan** [comment]
@antoniq Yeah, my question should be clarified. But first, appreciate if you can clarify the following:

Integration testing means different things, [Fowler for example, defines 3 types of them](https://martinfowler.com/bliki/IntegrationTest.html):
1. Testing microservice A who collaborate with B&C, we use the real B&C during the test
2. Testing microservice A who collaborate with B&C, we stub B&C
3. We test few components/layers of Microservice A

To which of the above options did you post refer?

**Comment by antoniq** [comment]
In connection to the article, we are using Narrow integration testing (2). Component testing covers more paths, but still does not use real running services.

**Comment by i0natan** [comment]
@antoniq Do you see any compelling reason to use narrow integration testing (e.g. 2 layers/classes under test) instead of a component test (the entire flow)?

My view is - if you already pay the integration price (setup an environment which includes DB), then go all the way and check the component * behavior, from the perspective of the *user/client, by simulating native system flows without mocking anything but external services. As a bonus coverage will also get higher. Integration test on the other end, will force to simulate some artificial scenario (e.g. test two layers) and demand more effort for less value
