### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by marcelosdm** [i0natan/nodebestpractices#223]
Hello everyone!

I just saw that this project already has the [issue 196](https://github.com/i0natan/nodebestpractices/issues/196), that's about the **Portuguese translation**. But it's all about the Portuguese from Portugal.

Wouldn't it be nice to have the translation to **Brazilian Portuguese** too?

If it's ok, could I help with it?

**Comment by i0natan** [comment]
Hey @marcelosdm, welcome aboard!

Will be honored if you can lead this translation. If you're up for the challenge - I'll be at your disposal should you need anything. I can create a branch for this work.

I would ask/recommend only 2 important guidelines:

Keep the same content & formatting - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and them translate
Duplicate pages - the content should be translated over a page duplication. Readme.MD became Readme.{language}.MD (where {language} means the language you're working on), all other files should be duplicated similarly. So the number of English & {language} pages should be the same. Will create a bold link from the English home page to the {language} home page (with bold credit of course...).

Your name will be on the top of the {language} page.

What do you think?

**Comment by marcelosdm** [comment]
Hello @i0natan !!

Wow!! I'm really excited and honored with your feedback!

I agree with those guidelines and I'd like to say that I'm ready to start!

So, I await for the new branch so I can start the translation.

Thank you very much!

**Comment by gilbertosil** [comment]
Hi, 

@marcelosdm  if you need help with the translation,  i would like to help you.

**Comment by marcelosdm** [comment]
Hey @gilbertosil !

I'm glad to hear from you!

Of course I'll need help!!

Feel free to join me!

**Comment by i0natan** [comment]
@marcelosdm @gilbertosil Opening a Brazilian-Portugese branch by tomorrow but anyway you may clone already, collaborate on the clone and periodically push to the branch Brazilian-Portugese. Does this makes sense?

**Comment by marcelosdm** [comment]
@i0natan I totally agree with that! I cloned yesterday and I'm already working on it.

Thank you so much in advance!

**Comment by marcelosdm** [comment]
By the way, @gilbertosil we should organize our work, so we don't repeat ourselves.

I'm already translating the **README.md** file! What do you think you can do by now?

Maybe the best practice is you clone my repo and make your PR to it, so we can make it the best way to the main project. What do you think?

And of course, anyone who read this is welcome to join us!

**Comment by gilbertosil** [comment]
Hi, 
@marcelosdm, sorry to be gone in the last few days, I'll make a clone of your repository.

**Comment by marcelosdm** [comment]
Hey @gilbertosil !

Welcome back friend!

I'm pushing some updates that I made recently (including today).

Please, make sure you're up to date!!

If you see anything and have any suggestion in those parts I translated, feel free to contact me.

See ya and keep going!

**Comment by annacruz** [comment]
Hey @marcelosdm do you need any help in pt-br translation?

**Comment by marcelosdm** [comment]
Hello @annacruz !!

Yes, I do!! You're very welcome to join me in this journey!!

Currently, I'm translating the **section 6** from the **Readme.MD** file.

So, if you could start translating the **section 7**, I think it'll be a great start!

By the way, feel free to read the translation I already did and do any typo that you see. Sometimes, even if we read our own work, we don't see our mistakes kkkk

Thank you so much!

**Comment by i0natan** [comment]
@annacruz Just saying welcome 👋 

@marcelosdm Sounds like a great progress, looking forward to see the end result

**Comment by yanmtbr** [comment]
Hey, @marcelosdm I would like to help it too. May could I start with the **sections folder**?

**Comment by marcelosdm** [comment]
> Hey, @marcelosdm I would like to help it too. May could I start with the **sections folder**?

Hello @yanmtbr ! Absolutly!! You'll be very welcome!

**Comment by sagirk** [comment]
Time to [merge](https://github.com/i0natan/nodebestpractices/pull/341#issuecomment-466666939) this translation to master! 🎉 

@marcelosdm Is it alright with you to open a new PR to master for this? 

I [tried](https://github.com/i0natan/nodebestpractices/compare/master...Brazilian-Portuguese), but there are merge conflicts to resolve.

**Comment by sagirk** [comment]
@marcelosdm PTAL at https://github.com/i0natan/nodebestpractices/pull/350.

**Comment by sagirk** [comment]
Final PR to move this into master: #351 ([Changes](https://github.com/i0natan/nodebestpractices/pull/351/files?w=1))

**Comment by marcelosdm** [comment]
> @marcelosdm I resolved the merge conflicts. PTAL at #350 to confirm that I didn't screw it up. 🙏

I just checked and saw that everthing is great!! 🙏🙏🙏

Thank you soooo much!
