### ISSUE TITLE
Translating the security section to Chinese

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#233]
@MattJin Greetings. It's been a while. 

We've added a new section - security best practices. If you happen to have time to update the Chinese pages - it would be great. I can help by adding the English section to the Chinese one and by creating all the chinese security pages in English

**Comment by MattJin** [comment]
Got it. I will update them recently and will create the Chinese pages myself.

**Comment by i0natan** [comment]
@MattJin That would be awsome
