### ISSUE TITLE
new practice suggestion: 

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#248]
> Logging is one of those things that can sometimes be a black box for developers. Maybe you have a dedicated DevOps person who takes care of logging infrastructure for you, or maybe it’s your first time working on this side of things.

https://www.coreycleary.me/why-should-your-node-js-application-not-handle-log-routing/

**Comment by i0natan** [comment]
@coreyc That's cool that you're here! Goes without saying that I enjoyed the article. How did you find this thread?

Looking forward to reading the PR. May I suggest that you take a quick look at our [writing guideliness](https://github.com/i0natan/nodebestpractices/blob/master/.operations/writing-guidelines.md)

**Comment by coreyc** [comment]
@i0natan I noticed some traffic coming to my blog from this link (I have very basic analytics setup, so often it'll just show github.com as the referrer link but this time it showed the full url). Also, I'm well aware of this project so I'm sure I would have stumbled upon this thread sooner or later!

**Comment by js-kyle** [comment]
This has been merged, thanks @coreyc !
