### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by refack** [i0natan/nodebestpractices#25]
I recommend [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) which AFAIK is equivalent to what Wikipedia use.

**Comment by i0natan** [comment]
@refack sounds good, can you update?

**Comment by i0natan** [comment]
@refack found it, doing that myself (keeping you for a bit more strategic challenges...)

**Comment by i0natan** [comment]
@refack can't see that license on the templates list 
![image](https://user-images.githubusercontent.com/8571500/32489584-2607fec2-c3b9-11e7-9c6b-1b5e2d1cb069.png)

**Comment by Calinou** [comment]
You can add [this file](https://github.com/idleberg/Creative-Commons-Markdown/blob/master/4.0/by-nc-sa.markdown) as `LICENSE.md` from [Creative-Commons-Markdown](https://github.com/idleberg/Creative-Commons-Markdown).

**Comment by i0natan** [comment]
done
