### ISSUE TITLE
Will it be possible to have a sample app which implements most of this best practices?

### ISSUE THREAD

**Issue by lightbringer2994** [i0natan/nodebestpractices#257]
I am a beginner nodejs developer and having a sample app would help in understanding the practices better, along with serving as a good starting point.

**Comment by i0natan** [comment]
@lightbringer2994 As @js-kyle we're actively working on this. Yet it might take some time.

If we present the drafts in a webinar, would you like to participate?

**Comment by lightbringer2994** [comment]
@i0natan Absolutely!

**Comment by Condell** [comment]
I'm actually really interested in this too. All the tutorials I've watched split Express apps up exactly how this guide says NOT to. So I'm trying to piece together my own "correct" makeshift Frankenstein project structure like the one mentioned in the "Structure by Components" section of this guide.

Even if it's not an entire project, it would be really helpful to know what exactly should go in each file. Maybe a small example of what should go in all the .js files listed under the "user" directory in the "Layer Your App" example?

**Comment by lightbringer2994** [comment]
If we can have a small app (or snippet) which demonstrates the "structure by components" best practice, it would save us a lot of confusion. @js-kyle, will this be possible? Thanks in advance!

**Comment by i0natan** [comment]
@Condell @lightbringer2994 Thank you. This will come the sooner we can, we're just focused on other workstreams like the performance section I hope to share with you some initial snippets in two weeks or so. I'll ping you here

/remind in 10 days

**Comment by lightbringer2994** [comment]
@i0natan, Just a gentle reminder. Even if its not finishe, it will be really helpful if we can take a look at something. Thanks in advance!

**Comment by lightbringer2994** [comment]
@i0natan , Any updates on this? Sorry If i am disturbing.

**Comment by NitinHsharma** [comment]
@i0natan I m sorry to interpret in between, I totally agree that you are busy in other sections which are on priority, Mean while is that helpful if you tell here what are you planning so that we (as new beginners) can start working on it and you or anyone else can correct/improve it. That will be more fun and helpful (just an option)

**Comment by aadikill** [comment]
@i0natan Any updates on this? Eagerly waiting this. Thanks in advance!

**Comment by i0natan** [comment]
@aadikill Updates - We're going to work on this on Christmas vacation and share some beta

In the interim, I really liked this starter https://github.com/talyssonoc/node-api-boilerplate by @talyssonoc

**Comment by RoncoCo** [comment]
@i0natan Any updates? Thanks in advance!!

**Comment by i0natan** [comment]
> @i0natan Any updates? Thanks in advance!!

Hey, really sorry but it was de-prioritized due to other projects that I'm working on 😿 . I'm focused now on improving my testing skills and writing about this experience.

I'll arrive to this sometime, but it will take months 😄

**Comment by talyssonoc** [comment]
In case you folks are still interested, we just release a new version of the node-api-boilerplate, more organized and built with TypeScript https://github.com/talyssonoc/node-api-boilerplate

**Comment by rluvaton** [comment]
Of course we are interested, community effort is always welcome
