### ISSUE TITLE
Publish a PDF

### ISSUE THREAD

**Issue by iamthadiyan** [i0natan/nodebestpractices#258]
Excellent collection. I learned a lot from this. Can you please consider publishing the content as a PDF file?

**Comment by BrunoScheufler** [comment]
@iamthadiyan @i0natan I really like that idea, especially considering we could reach additional devices types such as e-readers or PDF readers in general. It depends though if we create a PDF from the complete content or add the bullets first and follow up with the section pages. The first solution is simply a matter of rendering a markdown file (our main readme) to PDF, whereas the second way would require tools to stitch all sections together to one unified file.

**Comment by i0natan** [comment]
@iamthadiyan Welcome aboard and thanks for the nice idea. Where would you publish this PDF? why people would prefer reading via PDF?

@BrunoScheufler Any reputable tools that convert markdown to PDF?  

p.s. I do actually have all the entire repo, including inner pages, as a PowerPoint presentation which can be exported immediately as PDF. The caveat is that it gets obsolete with time (it was generated manually).

**Comment by BrunoScheufler** [comment]
@i0natan I'll see what I can do, know a few tools to do the job, otherwise I'll create a custom solution :+1:

**Comment by iamthadiyan** [comment]
As @BrunoScheufler said it makes offline reading easy and lookup faster. Also I personally prefer it that way :) @i0natan You are right, keeping the PDF up-to-date is a challenge in itself. But I believe it is worth the effort. 

Thanks again for the excellent work you guys are doing.

**Comment by i0natan** [comment]
@BrunoScheufler What would you prioritize: this or CI/code-standards?

**Comment by BrunoScheufler** [comment]
@i0natan I'd say both are important points, but if I had to choose one it'd be code standards/guidelines. But I'll also say that the PDF version/tooling is a separate project/workload that I'll happily work on in the next time 👍
