### ISSUE TITLE
October maintenance checklist

### ISSUE THREAD

**Issue by sagirk** [i0natan/nodebestpractices#268]
**Maintainer on call**: @sagirk 

**Updates**
- [x] Update top badges with best practices item count, last update date and Node.js version
- [ ] Ensure all translations are aligned with the English version

**Comment by i0natan** [comment]
@sagirk Until can we fill here stars and flowers?

**Comment by sagirk** [comment]
@i0natan PR is up @ https://github.com/i0natan/nodebestpractices/pull/281. PTAL.
