### ISSUE TITLE
[suggestion] testing planning best practices

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [i0natan/nodebestpractices#271]
So, I have a problem that I lack the knowledge to solve, and would love to see that knowledge shared on this repo.

My problem is that I currently write tests for the project that I work on in a not-so-organized matter, and when searching for testing-planning content/tutorials in Node.js, I came up short. I'd love to see some best practices discussing stubs, mocks, spies, test pyramids, this kind of thing.

My current project has a set of scenarios that can be expressed in certain sequential steps. I'd love to see how data is handled for testing purposes on big projects.

My current approach to do that is by having a big fat function that creates the scenario until a certain step to make the required conditions for my test, and then I run the actual assertion in my test, but that fails me a lot of the time, since I can't do smaller changes in between. 

Another approach would be to have a pre-defined database for each test case, but that can be a lot of work to do for each test case.

How do the pros handle it? Would that be a topic that fits in with the rest of the repo to write about in depth?

Meanwhile, can you recommend a good resource for learning intermediate testing stuff in Node for a testing newbie? A video course would be ideal, but I am open to books as well.

**Comment by js-kyle** [comment]
Great idea! I agree it would be great knowledge to collect here.

@i0natan will have some great opinions and knowledge on existing resources for this kind of thing 👍

**Comment by i0natan** [comment]
@AbdelrahmanHafez Welcome. 

I didn't fully understand your scenario, is it a data pipeline? something else? if you can describe your solution in greater details, the high-level components and their responsibility (feel free to obscure a bit if privacy is a concern), we can think together here on strategies. I might drug other testing experts to the discussion based on the topics.

I highly recommend this blog post, it's the most comprehensive article one can find which covers almost all the testing technique: https://medium.com/@copyconstruct/testing-microservices-the-sane-way-9bb31d158c16

**Comment by AbdelrahmanHafez** [comment]
I wrote a simplified example of how my scenario is like the following.

We have a system where I can create an account,request some items to be priced, receive offers on these items from sellers, pick some of these offers, and make an order with them, then make a payment on that order.

The dependency flow is like the following: user > request > order > payment.

So the way I test this is by having a function `createTestingScenario ` that actually creates the data for me on the DB for each test case, that encapsulates the actual functions inside it.

```js
// create.testing.scenario.js

const createUser = require('./users/create.js');
const createRequest = require('./requests/create.js');
const createOrder = require('./orders/create.js');
const createPayment = require('./payments/create.js');

async function createTestingScenario ({
  user = false,
  request = false,
  order = false,
  payment = false
}) {
  // building dependencies
  if (payment) order = true;
  if (order) request = true;
  if (request) user = true;

  let userId;
  let requestId;
  let orderId;
  let paymentId;

  if (user) {
    const user = await createUser({ some: 'data' });
    userId = user._id;
  }

  if (request) {
    const request = await createRequest({ userId, some: 'other data' });
    requestId = request._id;
  }

  if (order) {
    const order = await createOrder({ userId, requestId, even: 'more data' });
    orderId = order._id;
  }

  if (payment) {
    const payment = await createPayment({ userId, requestId, orderId, lo: 'and behold' });
    paymentId = payment._id;
  }

  return { userId, requestId, orderId, paymentId };
}
```

Here we use it in our `beforeEach(...)` block.

```js
// create.order.test.js

const { Order } = require('mongoose').models;
const assert = require('assert');

describe('createOrder(...)', () => {
  let userId;
  let requestId;

  beforeEach(async () => {
    const creationResult = await createTestingScenario({ request: true });
    userId = creationResult.userId;
    requestId = creationResult.requestId;
  });

  it('creates an order', async () => {
    const order = await createOrder({ requestId, userId, other: 'data' });

    const orderOnDatabase = await Order.findOne({ _id: order._id }).lean();
    assert.equal(orderOnDatabase.status, 'pending');
  });
});
```

This has been proving to be slow on the long run (1 minute for 150 test cases), and more importantly, it's becoming unmaintainable, as the real applications scenarios are not as linear as this version's scenarios are.

One way I've thought of doing things is creating fake data for each function in each test case, and stub it(not sure if this is the accurate term), but we add new fields to the schemas fairly often as the business requirements change, and I am afraid it's going to be a lot of effort to keep maintaing the fake data over time.

>I highly recommend this blog post

Thank you, I'll give it a read ASAP

>Next week I'm holding a webinar about the 'modern testing pyramid', it summarizes multiple advanced testing techniques - lmk whether you want to join

Definitely, Very interested. Is it invitational based? Can I send  you my E-mail on Twitter?

**Comment by i0natan** [comment]
@AbdelrahmanHafez Interesting case, thanks for bringing, I'm on a short trip so will probably have a deep look by Wednesday and then will share my thoughts. In the interim leaving here few questions to boost my understanding:

> We have a system where
Is this a monolith where all the referenced entities are mixed in a single module?

> One way I've thought of doing things is creating fake data for each function in each test case, and stub it(not sure if this is the accurate term),
Can you share few words about the 'create order' flow dependencies? Does the create order function approaches some request/user module or just retrieves directly from the DB the user and the request? Including a gist of the createOrder function/flow can really help

> This has been proving to be slow on the long run (1 minute for 150 test cases)
Over your CI or local developer machine? with parallelization (both Mocha, Jest and your CI can spread tests across multiple processes)?

> as the real applications scenarios are not as linear as this version's scenarios are
Optionally: Seems like this is where the real complexity exist, can you share an example of when things become hairy?

> Definitely, Very interested. Is it invitational based? Can I send you my E-mail on Twitter?
Sure, I'll be glad to. My Twitter is @goldbergyoni. The webinar is probably deferred to next week (Yes, invitation-based)

**Comment by i0natan** [comment]
@AbdelrahmanHafez I'm going to look through this on Sunday, see if you can share the details by then

**Comment by AbdelrahmanHafez** [comment]
@i0natan I've been trying to find some time to write a detailed answer. I am planning to give a detailed answer with an example project before Sunday.

**Comment by AbdelrahmanHafez** [comment]
@i0natan I just finished up writing [an example project](https://github.com/AbdelrahmanHafez/node-testing-example) that abstracts my situation.
A user creates an account, then creates a request, then creates an order with that request.

>Is this a monolith where all the referenced entities are mixed in a single module?

Frankly, I am not sure if this is a monolith or not. I'd say it's not, I separate modules into different folders, and each contains its own logic, but Facing difficulties with the project makes me doubt that I am doing something wrong. Would love it if you point out bad structural decisions so I can avoid them in the future.

>Can you share few words about the 'create order' flow dependencies?

Well, when a user creates their account, then create a request, some stuff on the ground happens, then the user can create an order.
Creating an order requires validating that the request belong to this user, and maybe some other conditions that require having to call things from the Request/User module.

>Over your CI or local developer machine? with parallelization (both Mocha, Jest and your CI can spread tests across multiple processes)?

On my local developer machine. No parallelization, because my testing actually calls the database, which is mainly why the tests are slow.

>Seems like this is where the real complexity exist, can you share an example of when things become hairy?

Oh, yes! That's exactly when things get interesting. This strategy fails me when I want to do modifications in the middle of the scenario, which (in the real application) is a lengthy scenario (up to 50 entities). For example, if I want to create 3 requests and a single order for these requests, I can't use the `createTestingScenario(...)` function, I have to re-write all the logic from the beginning of the scenario in the `beforeEach(...)` block.

>Sure, I'll be glad to. My Twitter is @goldbergyoni. The webinar is probably deferred to next week (Yes, invitation-based)

Am I too late for that? If not, I can't reach you on Twitter, your DM is not available and I don't wanna post my E-mail on Twitter for privacy reasons. I would appreciate it a lot if you send me something on @AHafez0 so I can send you my E-mail.

**Comment by i0natan** [comment]
@AbdelrahmanHafez On it...

**Comment by i0natan** [comment]
@AbdelrahmanHafez 

Hey, had a deep look within the code, it looks very nice and absolutely attempting to create autonomous components. Following are my thoughts.

**First, consider some architecture change**
Before discussing the testing, one major architecture-level concern: Keep the components truly autonomous - if you separate the whole into small problems - you get simpler problems. You are doing great steps toward this direction (separate folders) but you also mix the same DB, ODM models and this centralization complicates everything. For example, each test suite must take care to feed the DB with related entities which leads to that one big "createTestingScenario".

Instead consider making each component own its own resources/collections so the problems it tests is smaller (e.g. each component might user a different DB instance of product). If Order needs to get some Request - it should be done by approaching the Request component and not the mongoose model. DB was not meant for integrating components. This way you draw clear boundaries between a component with almost no dependencies.

By doing so, each test shouldn't care to fill the DB with sibling-components data - it just need to define stubs that return pseudo data. For example:
it("Scenario - valid order properties, Expect - get valid new order" , () =>{
//sinon - mocking/stubbing framework
sinon.stub(requestService, "getbyId", () => return {id:...);
const { code, message, orderId } = await Order.add({ order: { requestId } });
assert.equal(code, 1);
})

All that said, doing this change might not be feasible immediately, mostly if you're DB already mixes the data sources. Rest of the thoughts below don't assume you're doing this change

**Thoughts on the testing design**
If you keep each test case independent and avoid centralization, you may avoid high complexity ("big fat functions" like createTestingScenario). Let each test case prepare its own ground and tells the entire story alone, no dependencies and assumptions. For example (assuming you didn't perform the architectural changes):
it("Scenario - order for un-confirmed user, Expect - get refuse response" , () =>{
const user = testHelper.addNewUser({name:Yoni, status:notConfirmetYet})
const { code, message, orderId } = await Order.add({user });
assert.equal(code, "cantAcceptOrdersForNonConfirmedUsers");
})

This is the ideal setup in terms of maintainability - each test case is an independent and small problem. Now performance might become the challenge, here are few thoughts on how to mitigate this:
1. 1 min is not that bad for getting full confidence that all your layers are playing nicely together
2. Tag critical/sanity tests, those that test the basics, run them first, get feedback in 20 seconds, then run the rest
3. If you separate into multiple components (my architectural change proposal)then you might just run the test of each component separately (why run Request tests if you performed a change within User)
4. Use in-memory DB for testing (Mongo, for example, supports this)
5. Share state among tests that don't mutate data - tests that just query for data, might generate initial state on beforeAll, the state should be explicit (e.g. a file level variable that states which objects were inserted), e.g.
it("Scenario - get order of existing request, Expect - get valid response" , () =>{
const { code, message, orderId } = (await Order.getById(preLoadedData.existingRequest);
assert.equal(code, "cantAcceptOrdersForNonConfirmedUsers");
})
6. Parallelize tests - Jest, Mocha and most CIs know to run tests across multiple processes, now that your tests are independent this is feasible and might yield big performance win

Thoughts?

**Comment by i0natan** [comment]
@AbdelrahmanHafez Forgot to write, the webinar will take place in 2 weeks. Drop me an email to me at goldbergyoni dot come

**Comment by i0natan** [comment]
@AbdelrahmanHafez Sorry for the long pause, had some busy days...

> I am not sure I understand it fully, would that mean we have a class Request that would have a Model (mongoose model) under it...

The main principle is: if these are *autonomous components*, you can't assume they reside on the same server, neither they share the same DB -  hence can't refer directly to JS files rather approach only via the network (e.g. http REST): Order needs something from Request? it should approach via the network to the Request server. For convenience, at the start they might exist on the same server, but for scale purposes, your code can't assume that.

How? there might be multiple design for this but anyway you are going to implement this will push you toward smaller problems === no need for huge setup methods rather just feed 1-2 entities into DB during testing. Many people asked here recently how exactly the project should be structured and I'll really try to conduct some web meeting next week and demonstrate some example!

> Is there something else that I am missing here? If not, wouldn't that be repeating code unnecessarily? What do you think are the pros and cons to having the conditions in the it(...) clause over beforeEach(...)?

Nothing else, just autonomous and self-explanatory testing. Otherwise, If ~50 tests assume, interact with and maybe mutate the same set of data you get a big fragile centralized design that will be hard to maintain. However, If any test creates its own data as I suggest - you can easily understand it + it will always stay a small isolated problem.  Have a testing bug? just have a look at 7 lines of test and solve it, no hidden and fragile dependencies. I would classify this as super-critical

> Stubs would work with the current pattern as well, am I correct?

I don't think so. Becuase in the current design, your modules share the same DB so when inserting a new Order, the DB might enforce that a Request or User already exists in the DB so you can't mock/stub it. For example, if instead of inserting a real Request you stub it, then when inserting a new Order the DB layer might throw an exception and say - "No Request here". The entities/modules are mixed on the DB level as well - the software is not allowed to assume that one entity can be saved without the other. On the other hand, if the Request is a totally different component, then for sure the Order DB doesn't assume anything about Request. Is this point clear enough?

> I am afraid that stubbing would make things more error-prone

I don't think so. Example: You have a getRequest stub which returns 3 fields. Now someone added a new Request field in the DB. Option A -> your test need to refer to this new field (you want to assert something), so anyway with/without stub you would have to change the tests... Option B -> your test doesn't refer to the new field, then also don't change your stub...

> I gave that a shot way back, and the results weren't as good as I expected. In fact the tests ran slightly slower.

Interesting, is this some corner case or something by design? why use this package (haven't look into it thoroughly) and not just configure Mongo for memory store?

**Comment by AbdelrahmanHafez** [comment]
>The main principle is: if these are autonomous components, you can't assume they reside on the same server

Looks clear to me, and I agree that would be much cleaner. Although it would introduce some complexity in the sense that sending commands via a REST API would be much more difficult than a simple command, for example if I want to do `Request.findOne(...).select(...).populate(...);` I can see how to do it if modules reside on the same server, because we have access to the mongoose model.

>Nothing else, just autonomous and self-explanatory testing.

>Saw today some similar case of relying on global hooks, put my thoughts here

Totally agree, it's much more explicit and easier to work with. This is a standard I am following from now on.

>I don't think so. Because in the current design... when inserting a new Order the DB layer might throw an exception and say - "No Request here".

Having components on different servers would _guarantee_ that things aren't mixed, but would that mean it's impossible to work with stubs and mocks when they reside on the same server? When you say that the DB layer might throw an exception, what exactly is the DB layer in our example?

Let's take this function as an example, what could go wrong if we stub the Request.findOne(...) to return pre-defined data?
```js
async function createOrder ({ order }) {
  const { User, Request, Order } = require('mongoose').models;

  const request = await Request.findOne({ _id: order.requestId, userId: order.userId });
  if (!request) throw new Error('Request does not exist.');

  const createdOrder = await Order.create(order);
  return { code: 1, message: 'Created order successfully.', orderId: createdOrder._id };
}
```

>I don't think so. Example: You have a getRequest stub which returns 3 fields...

Makes sense.

>Interesting, is this some corner case or something by design? why use this package (haven't look into it thoroughly) and not just configure Mongo for memory store?

It was something by design, I abstracted the issue by inserting/reading 100k docs, the performance was slower with that package than running things normally. Didn't configure Mongo for memory store because I didn't know it existed. 😄 

I have a couple of questions related to the subject of testing. 

1. Wouldn't stubbing make it possible to write tests for anything at all without having to worry about having dependency builders (e.g. createTestingScenario)? Is this a right assumption? Because I find myself at times overwhelmed by having to work on a complicated testing dependency, and this seems like a perfect solution to increase the accessibility of writing tests, I'd like to know what you think on that.

2. How would one go about testing reading/writing from the DB? For example I wanna make sure that the query that I am writing actually fetches the document that I want. Is it okay to read from the DB directly in this case?

P.S: I think this thread is going to get lengthy, I am trying to ask all the questions I have on mind that other people might have later on when reading the thread, so that later on we can have Q&A out of that thread for those who are new to testing.

**Comment by i0natan** [comment]
@AbdelrahmanHafez 

In the interim I uploaded my session about advanced testing techniques here, the 1st on the list (component) might suit your needs (will answer shortly)

https://youtu.be/-2zP494wdUY

**Comment by AbdelrahmanHafez** [comment]
>In the interim I uploaded my session about advanced testing techniques here

Thanks a lot for the quality content, and looking forward for more. You seem to be well-versed when it comes to testing and testing strategies, I believe there's a good potential to enrich the node community with your testing knowledge, and fill the gap, beyond the typical `expect(add(1, 2)).to.equal(3);` tutorial.

>will answer shortly

Can't wait for it!

**Comment by i0natan** [comment]
> beyond the typical expect(add(1, 2)).to.equal(3); 😆 

Sorry for the delay, it's on my todo list. Very much behind my entire todos

**Comment by AbdelrahmanHafez** [comment]
Totally understandable; Take all the time you need. 😄

**Comment by i0natan** [comment]
@AbdelrahmanHafez Sorry for answering the later questions in a timely manner, do you still have testing concerns?

p.s. I've posted some best practices here, LMK if you want to help in PRing them here:
https://medium.com/@me_37286/yoni-goldberg-javascript-nodejs-testing-best-practices-2b98924c9347
