### ISSUE TITLE
Can I help improve Chinese translation?

### ISSUE THREAD

**Issue by rhinonan** [i0natan/nodebestpractices#304]
I'm writing somthing about nodejs for my company, and I found this. But translation of chinese was not prefect. So, can i do something for it ?

**Comment by MattJin** [comment]
@rhinonan yes, welcome.

**Comment by i0natan** [comment]
@rhinonan Welcome!

@MattJin Is the master of our Chinese, I suggest you PR (or share here) edits and let @MattJin review

Thanks for help improving this guide 🙌

**Comment by MattJin** [comment]
@rhinonan You can also help to translation some bullets. If you like, you can join us.

**Comment by i0natan** [comment]
@MattJin Feel free to close the issue when done

**Comment by MattJin** [comment]
Get it. @i0natan
