### ISSUE TITLE
Performance List of Generic Bullet points

### ISSUE THREAD

**Issue by TheHollidayInn** [i0natan/nodebestpractices#315]
Continuing from: https://github.com/i0natan/nodebestpractices/pull/288#issuecomment-450572627. As suggested, let's discuss a list of bullet points to be added to our generic list.

Looking at this: https://github.com/i0natan/nodebestpractices/issues/302, here are a few that seemed to be good:
- Use text compression
- Deal with database and external APIs in batches
- Benchmark slow db calls
- Analyze repeated API Calls/Database Queries to cache them
- Serve static assets from a CDN

Are these good? and what else should we add?

Also, the format will be similar to this: https://github.com/i0natan/nodebestpractices#-65-collection-of-generic-security-best-practices

**Comment by i0natan** [comment]
@TheHollidayInn Perfect 🎖 

Just try adding some more info & links to each (when the implementation tools are highly popular and standard), for example:
"Benchmark slow db calls" - share link to Postgres & mySQL query plans and slow queries profiling

Let's start refining this using a PR?

**Comment by i0natan** [comment]
@TheHollidayInn Didn't you have another performance PR? I suddenly can't find it...

**Comment by TheHollidayInn** [comment]
Will do! I'll open a PR and add more.

Here is the other part I was working on: https://github.com/i0natan/nodebestpractices/issues/294#issuecomment-450262446. I posted the initial thoughts in the issue per your request. I can switch it to a PR if you'd like!

**Comment by i0natan** [comment]
@TheHollidayInn Great, so I'm following on  #320 & #294

**Comment by i0natan** [comment]
Closing as we're engaged on the PR #320
