### ISSUE TITLE
Use images w/ transparent background – dark theme FTW

### ISSUE THREAD

**Issue by scorphus** [i0natan/nodebestpractices#321]
First of all, thanks for these best practices!

Just like many others, I use a [dark theme](https://github.com/StylishThemes/GitHub-Dark) for GitHub with [Stylus](https://github.com/openstyles/stylus/):

![image](https://user-images.githubusercontent.com/2112697/51123966-75252e80-181d-11e9-9baa-12068c3c75b5.png)

![image](https://user-images.githubusercontent.com/2112697/51124342-655a1a00-181e-11e9-847b-cbf38f9e8c94.png)

This amazing best practices would look a bit better on dark themes if those images had transparent background.

I'd love to change that and submit a PR. And it would be much easier if I had the original image files, if that's even possible.

**Comment by js-kyle** [comment]
Hey @scorphus - cool idea, a PR for this would be welcomed! I'll try to find out if those files are available before you start

**Comment by i0natan** [comment]
@scorphus Sounds interesting, can the user opt-in/out? where can I see an example? Kindly elaborate how it works

**Comment by scorphus** [comment]
> @scorphus Sounds interesting, can the user opt-in/out? where can I see an example? Kindly elaborate how it works

I'm not sure I get it, but I'll try to elaborate. Pardon me if I got it wrong. An image with transparent background blends itself with the background it's on top of.

In theory, it could be seen as a kind of opt-in/out. That is, depending on what background colour the user defines, the image will have that background colour. But in reality, no. The image will be the same for every single user.

[In this example](https://github.com/scorphus/nodebestpractices/tree/banner-transp-bg), the banner has transparent background.

By the way, we can start with the banner: #327

Thanks!

**Comment by i0natan** [comment]
Got it, so we basically need to make the banner and other images transparent?

**Comment by i0natan** [comment]
@idori Do we have those?

**Comment by idori** [comment]
@i0natan yes, I'll re-make the header with a transparent background and check which other images require work to be dark mode friendly

**Comment by i0natan** [comment]
Thanks @idori
