### ISSUE TITLE
Jan 2019 thank you

### ISSUE THREAD

**Issue by js-kyle** [i0natan/nodebestpractices#333]
Thank you to @Berkmann18 for writing and working through our feedback on our first best practice from the new performance section, 7.1. Prefer native JS methods over user-land utils like Lodash 

https://github.com/i0natan/nodebestpractices#-71-prefer-native-js-methods-over-user-land-utils-like-lodash

🎉🏆

**Comment by Berkmann18** [comment]
My pleasure 😄.
