### ISSUE TITLE
Update 'Avoid Eval' to include new Function

### ISSUE THREAD

**Issue by LewisArdern** [i0natan/nodebestpractices#343]
Dynamic execution of JavaScript also happens in new Function, which is even referenced here: https://github.com/i0natan/nodebestpractices#-615-avoid-javascript-eval-statements, so this should be included. 

Pull request #342

**Comment by js-kyle** [comment]
Thanks heaps for the PR! It has been merged

**Comment by i0natan** [comment]
@LewisArdern Thanks for this great addition
