### ISSUE TITLE
'npm security best practices' is a great source for additional security bullets

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#346]
Great article by @lirantal here: ["npm security best practices"](https://snyk.io/blog/ten-npm-security-best-practices/)

Some of the ideas there might be a great addition to our guide, we may include with Credit, what do you think @js-kyle ?

**Comment by js-kyle** [comment]
Amazing work! Yes definitely

**Comment by lirantal** [comment]
I'd be happy if you include credits and reference to the cheat sheet ;-)

**Comment by js-kyle** [comment]
I think 3.Minimize attack surfaces by ignoring run-scripts would be good to add here

**Comment by i0natan** [comment]
@lirantal Wouldn't this (ignore run-scripts) break some packages that rely on scripts?

@js-kyle Maybe bullet #1 (use .npmignore or files) is less controversial?

**Comment by lirantal** [comment]
> @lirantal Wouldn't this (ignore run-scripts) break some packages that rely on scripts?

Yep, and at the same time protect you from evil execution in install phases.
