### ISSUE TITLE
Improvements to commonsecuritybestpractices.md 

### ISSUE THREAD

**Issue by LewisArdern** [i0natan/nodebestpractices#348]
Did not like that OWASP A7 only included 'use CSP', so updated that to reference more content from OWASP with some slight changes to reflect node, e.g use a template engine.

Made some slight changes to the content for grammar improvements

https://github.com/i0natan/nodebestpractices/pull/347

**Comment by js-kyle** [comment]
Thanks heaps @LewisArdern
