### ISSUE TITLE
🎉🎉 Thank you contributors! 🎉🎉 (Feb 2019)

### ISSUE THREAD

**Issue by sagirk** [i0natan/nodebestpractices#354]
🎉🎉 The Node.js best practices guide has gotten even better during February, thanks to the many awesome contributions made by the following folks 🎉🎉

🌻 [Hozefa](https://github.com/hozefaj)
🌻 [Ethan](https://github.com/el-ethan)
🌻 [Sam](https://github.com/milkdeliver)
🌻 [Arlind](https://github.com/ArlindXh)
🌻 [Teddy Toussaint](https://github.com/ttous)
🌻 [Lewis](https://github.com/LewisArdern)

We realize that a lot of you contribute in your spare time, and would like to acknowledge the fact! Thank you so much for choosing to spend your time on this, instead of the very many other things you could have been doing! 🏆

Hope to see many of you hang around and contribute again! 💯

Cheers! 🥇

---

In addition, we now have a translation of this guide available in [Brazilian Portuguese](https://github.com/i0natan/nodebestpractices/blob/master/README.brazilian-portuguese.md) 📝 for all. Its availability announcement is now [featured in the `News` section](https://github.com/i0natan/nodebestpractices#latest-best-practices-and-news).

❤️❤️ Heartfelt thanks to @marcelosdm who relentlessly worked on it for months and saw it through to completion! Hats-off, Marcelo! ❤️❤️

**Comment by i0natan** [comment]
Great post @sagirk !!!

**Comment by marcelosdm** [comment]
Thank you all for this opportunity! ❤
