### ISSUE TITLE
April 2019 maintenance list

### ISSUE THREAD

**Issue by BrunoScheufler** [i0natan/nodebestpractices#378]
**Maintainer on call**: @i0natan

**Updates**
- [ ] Update top badges with best practices item count, last update date and Node.js version
- [ ] Ensure all translations are aligned with the English version
- [ ] Update 'thank you' stars & flowers
- [ ] Notify and thank the contributors of the month
- [ ] Update news and updates
- [ ] Tweet it!

**Flowers**
- @Invvard 
- @romulogarofalo 
- @thoqbk
- @Qeneke
- @MartinMuzatko

**Stars**

**Translation work**

**Comment by BrunoScheufler** [comment]
@i0natan @sagirk @js-kyle not sure who's leading the maintenance this month, do you guys have a clue? 😄

**Comment by i0natan** [comment]
https://github.com/i0natan/nodebestpractices/blob/master/.operations/operations-manual.md

I'm the one
