### ISSUE TITLE
express-jwt-blacklist default values should not be recommended

### ISSUE THREAD

**Issue by fabiancook** [i0natan/nodebestpractices#383]
Referencing: https://github.com/i0natan/nodebestpractices/blob/master/sections/security/expirejwt.md#express-jwt-blacklist-example

`express-jwt-blacklist` explicitly says not to use the default in memory cache for production, meaning it is not best practice, it should be pointed out that memcached or redis should be used in conjunction with `express-jwt-blacklist` so revoked tokens will be retained across processes.

**Comment by i0natan** [comment]
@BrunoScheufler Shouldn't this be assigned to @js-kyle our security expert?

**Comment by BrunoScheufler** [comment]
@i0natan probably, yes! Will reassign

**Comment by js-kyle** [comment]
@fabiancook Cheers for pointing that detail out, it has been updated 👍
