### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by georgem3** [i0natan/nodebestpractices#384]
I can help with the german translation -- progress will be slow(ish) though, so if anyone is willing to chip in, let me know.

**Comment by BrunoScheufler** [comment]
@georgem3 awesome, I could try to help out here as well 😄  Just start if you feel like it and simply submit a PR to the `german-translation` branch to save progress and make it available for other potential contributors 👍 If you need anything, let me know 👌

**Comment by georgem3** [comment]
Great! I saw the closed issue, but I must have missed that the branch is still active 😅

**Comment by BrunoScheufler** [comment]
@georgem3 I've just opened the branch since the previous translation attempt didn't kick off as hoped but now we'll try again! 😄
