### ISSUE TITLE
Error handling for promises outdated by a little :)

### ISSUE THREAD

**Issue by benjamingr** [i0natan/nodebestpractices#4]
Hey, in https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/catchunhandledpromiserejection.md and in the README you mention that exceptions are swallowed by default - but that hasn't been the case for a while :)

I can dig up the PR where we changed the default to log if you'd like - I think it was in 7.6

**Comment by i0natan** [comment]
@benjamingr yap, this section was written a year ago and is now outdated. Will be honored if you'll PR the change but I can do that as well. Thanks.

**Comment by i0natan** [comment]
@benjamingr fixed, thanks for the notice
