### ISSUE TITLE
Change 4.9 from Docker compose to Testcontainers

### ISSUE THREAD

**Issue by andreybleme** [i0natan/nodebestpractices#413]
Hi, Thanks for the great repo!

While reading the [4.9 Use docker-compose for e2e testing](https://github.com/i0natan/nodebestpractices#-49-use-docker-compose-for-e2e-testing) section I couldn't agree more that using some container orchestration strategy for e2e testing is a smart decision. But it can be painful to orchestrate the start/stop of this containers (people often do it using shell script).

In order to have our containers provided on demand and to have a more fine-grained control over them during our test execution, a pretty good approach is to use [testcontainers](https://github.com/testcontainers). It's actually a wrapper for the Docker SDK and it works really well for integration test scenarios. This approach fits very well with the "4.4 Avoid global test fixtures and seeds, add data per-test" practice.

Do you guys also think it's worth to add this somewhere in the docs? If yes, I can open a PR.
Thanks again :100:

**Comment by i0natan** [comment]
@andreybleme Welcome aboard, happy to brainstorm this important topic

My rough thoughts and questions:
1. I'm not sure that this advice is updated at all - in the K8S/Terraform/automation era, where it's much easier to replicate a production environment everywhere, I would avoid docker-compose AND any other tech/format that is not identical to the production. Why? (1) less realistic (2) another artifact to maintain. Simply put, I would advice a developer to run his local tests over minikube/competitors, and from CI run broad tests on a production namespace. Thoughts?

2. Why wouldn't the containers stop? we run the tests locally, once it finished we can teardown the docker-compose or remote k8s, what do I miss?

**Comment by andreybleme** [comment]
Right... :heavy_check_mark: 

Avoid using components that does not look like a production environment is a must. Agreed. But sometimes docker-compose it exactly a production-like environment, isn't it? 

The section I've linked: ["Use Compose for e2e"](https://github.com/i0natan/nodebestpractices#-49-use-docker-compose-for-e2e-testing), highlights that "Docker-compose turns this problem into a breeze by crafting production-like environment using a simple text file and easy commands."

So adding testcontainers as a suggestion for the docs seems to me a good idea, since it makes even easier to create an isolated network for e2e test by helping us to keep a stateless environment that is invoked not only before each test suite but also provides great flexibility to create this stateless isolated environment for a specific test scenario, during the test execution, or after a specific method invocation. It's a way more fine-grained control. Maybe I'm missing something as well about how we can programmatically control this testing environment with such a great control during the execution of a particular step of a test case, not only for the entire suite or the entire test case. 

What do you think?

**Comment by i0natan** [comment]
> Agreed. But sometimes docker-compose it exactly a production-like environment

hmm Are you familiar with a production that is based on docker-compose? :) Yeah, I know, it's written here, I wrote it actually, I was maybe right in 2017 when docker-compose was as similar to production as it could be, but in 2019 we can use EXACTLY the production technology (e.g. minikube)

> So adding testcontainers as a suggestion for the docs seems to me a good idea

Given that 95% will use K8S or Serverless in the next few years, they will benefit two great things in this regard:
1. It's very easy to run locally/CI using the same deployment language that is used in production (e.g. minikube for K8S, AWS SAM for Lambda)
2. It's relatively easy to run tests directly on the REAL production (e.g. K8S namespace)

Can testcontainers beat this?

**Comment by andreybleme** [comment]
Honestly I didn't know Minikube and such tools for running K8S locally...
"Given that 95% will use K8S or Serverless in the next few years", I'm honestly not sure about this, but I do hope so :)

Given things you have pointed out I see testcontainers as a good OPTION then (not necessarily a better one). It does not "beat" alternatives, but it is definitely an approach it's worth to know/try.

So far so good. Thanks again, good talking.
:boat:

**Comment by i0natan** [comment]
@andreybleme It was my pleasure discussing this, we may consider adding this but we first clarify what exactly is the added-value of testcontainers
