### ISSUE TITLE
Update medium security article

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#415]
@js-kyle Would you be able sometime to update the medium security article with the latest and greatest practices that you added here?

**Comment by js-kyle** [comment]
That is done now (Still top on Google too, 👍)

**Comment by i0natan** [comment]
😄 💃 🍾 🎈

**Comment by animir** [comment]
@js-kyle Hey, I still see old content here https://medium.com/@nodepractices/were-under-attack-23-node-js-security-best-practices-e33c146cb87d

**Comment by js-kyle** [comment]
Hey @animir I've updated 6.2 - is there if there are other things out of date, could you please point those ones out? Thanks

**Comment by animir** [comment]
@js-kyle 6.12 is outdated

**Comment by animir** [comment]
@js-kyle `express-brute` package which is listed in 6.12 has officially known vulnerability https://www.npmjs.com/advisories/823

**Comment by js-kyle** [comment]
Those older references have been removed now

**Comment by animir** [comment]
@js-kyle 6.12 `Read More: Login rate limiting` still leads to the old https://github.com/goldbergyoni/nodebestpractices/blob/security-best-practices-section/sections/security/login-rate-limit.md

**Comment by js-kyle** [comment]
Whoops, it's pointing to master branch now

**Comment by animir** [comment]
@js-kyle Almost there 👍 
`Read more` leads to the root readme file, and developer sees the same content as on medium 6.12 article. It is slightly inconsistent. Could you fix it, so `Read more` leads here https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/security/login-rate-limit.md

**Comment by js-kyle** [comment]
@animir Good catch again, that is the correct link now!
