### ISSUE TITLE
2019 june list

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#421]
**Maintainer on call**: @sagirk  

**Updates**
- [ ] Update top badges with best practices item count, last update date and Node.js version
- [ ] Ensure all translations are aligned with the English version
- [ ] Update 'thank you' stars & flowers
- [ ] Notify and thank the contributors of the month
- [ ] Update news and updates
- [ ] Tweet it!

**Flowers**
- @autoboxer 
- @bikingbadger
- @ChangJoo-Park
- @MasahiroSakaguchi
- @autoboxer

**Stars**

**Translation work**

**News**
- Enhanced Chinese translation

**Comment by js-kyle** [comment]
@i0natan is this meant to be June? I have already completed May

**Comment by i0natan** [comment]
> @i0natan is this meant to be June? I have already completed May

Yeah, my fault, fixed that
