### ISSUE TITLE
SyntaxError: Unexpected token throw

### ISSUE THREAD

**Issue by EvgenyOrekhov** [i0natan/nodebestpractices#43]
https://github.com/i0natan/nodebestpractices/blob/c0e1264dfe2161986a8c91e3df7df8d1d51b8785/sections/errorhandling/asyncerrorhandling.md#code-example--using-promises-to-catch-errors

This example has a syntax error:

```javascript
doWork()
 .then(doWork)
 .then(doOtherWork)
 .then((result) => doWork)
 .catch((error) => throw error) // SyntaxError: Unexpected token throw
 .then(verify);
```

`throw` is a statement, it should be wrapped in `{}`:

```javascript
 .catch((error) => {throw error;})
```

**Comment by EvgenyOrekhov** [comment]
Another one here: https://github.com/i0natan/nodebestpractices/blob/c0e1264dfe2161986a8c91e3df7df8d1d51b8785/sections/errorhandling/failfast.md#code-example-validating-complex-json-input-using-joi (it also has a missing `new` before `Error`).

**Comment by i0natan** [comment]
@EvgenyOrekhov nice catch! can you kindly PR it? thanks for improving this guide
