### ISSUE TITLE
Update Istanbul/NYC package links

### ISSUE THREAD

**Issue by ziyaddin** [i0natan/nodebestpractices#445]
I think [Istanbul/NYC](https://github.com/gotwarlost/istanbul) link in [section 4.8](https://github.com/i0natan/nodebestpractices#-48-check-your-test-coverage-it-helps-to-identify-wrong-test-patterns) should be updated to non-deprecated version links: [Istanbul](https://github.com/istanbuljs/istanbuljs) and [NYC](https://github.com/istanbuljs/nyc).

**Comment by i0natan** [comment]
YUP, thanks. Any chance you want to PR this change?

**Comment by ziyaddin** [comment]
Done.
