### ISSUE TITLE
Commit messages best practices

### ISSUE THREAD

**Issue by 0x80** [i0natan/nodebestpractices#47]
Since commit messages are an important part of coding practice, I think it would be useful to include that too.

I go by [these rules](https://github.com/erlang/otp/wiki/Writing-good-commit-messages)

**Comment by i0natan** [comment]
@0x80 this is very true and truly important yet this guide is focused on Node.JS topics only or topics that need specific examples in Node.JS. GIT flow is platform agnostic so I think shouldn't include it. I'd love to see other ideas from you
