### ISSUE TITLE
should probably suggest `rc` for 1.5

### ISSUE THREAD

**Issue by nwwells** [i0natan/nodebestpractices#50]
[`rc`](https://www.npmjs.com/package/rc) is a more popular config tool than `nconf` and `config`, is used by many rock-solid tools out there, and checks all the boxes you require. I'd suggest recommending it for config management.

**Comment by i0natan** [comment]
@nwwells good point!

can you elaborate how it stacks against those two? any differences/downside?

**Comment by nwwells** [comment]
I've never used the other two, tbh, but it supports everything I saw in the brief look that I had at the other two, including:

file (with recursive up-tree search)
option parsing
env vars
programmatic defaults and overrides

**Comment by i0natan** [comment]
it also more popular, makes sense to add it, can you kindly PR?

**Comment by nwwells** [comment]
Will do. Hopefully tonight

**Comment by nwwells** [comment]
Closed with #66
