### ISSUE TITLE
Issues with Use tools that automatically detect vulnerabilities

### ISSUE THREAD

**Issue by yonjah** [i0natan/nodebestpractices#51]
The entire page seems like it was kinda copy pasted out of a template  and does not provide any meaningful information.

The one paragraph explainer is mostly a quote but the next section is almost the same quote
with no working links to the original article.

There is no links to the actual tools being recommended 

The last paragraph is not an nginx config as the title suggests nor relevant to this topic

If I understand the content right the title should be changed to -
`Use tools that automatically detect vulnerable dependencies'
Since the original title sounds more like some kind of automatic penetration testing tool.
This is probably should be done way before production so the section is not really correct

I'll try to submit a pull request with changes but this should probably be part of the security section and not production and following this issue #33  it seem like this section is not going to be available anytime soon

**Comment by i0natan** [comment]
@yonjah you're right, content is not optimized there. Absolutely should be treated soon. Would you like to PR?

We're about to release milestones plan soon, security is planned for December end (to ensure the content is highly curated). Would love to see you part of that team.

**Comment by yonjah** [comment]
> Would you like to PR?
Submitted a PR -
https://github.com/i0natan/nodebestpractices/pull/52

I hope I'll have time to contribute at least one or two points mentioned in #33

**Comment by BrunoScheufler** [comment]
I think I'll prototype some of the ideas this week and finish the first point I already made! You can simply add your additions to the branch I created via PRs!

**Comment by i0natan** [comment]
@BrunoScheufler this one was merged and can get closed, right?

**Comment by BrunoScheufler** [comment]
@i0natan yeah!

**Comment by i0natan** [comment]
@BrunoScheufler feel free to close issues :)
