### ISSUE TITLE
Add const array/object note

### ISSUE THREAD

**Issue by davesnx** [i0natan/nodebestpractices#53]
Hey, I wanted to propose a simple note on this section: `3.7 Prefer const over let. Ditch the var`

Using `const` for arrays and objects doesn't mean that those can't change. Indeed, you can `push/concat/whatever` (doesn't matter if it's a mutable or immutable method) an array being a const.

Happens the same on objects, you can update the keys inside an object declared by a const.

**Comment by BrunoScheufler** [comment]
Yeah the const will only disallow reassignment. Invoking anything else will work by default. This is although more a language thing but we might reconsider it!

**Comment by i0natan** [comment]
@BrunoScheufler I believe that many developers not aware of this subtle pitfall

```
const a = [{},{}]
a[0].name = 'foo'
//works fine
```

It's mostly a question of real estate - is it important enough to fit in the TL&DR? hmm not sure :)

@davesnx thanks
