### ISSUE TITLE
Architecture by components is called in mi mind: Screaming Architecture.

### ISSUE THREAD

**Issue by davesnx** [i0natan/nodebestpractices#54]
Wanted to add this resource and the name:

https://8thlight.com/blog/uncle-bob/2011/09/30/Screaming-Architecture.html

**Comment by i0natan** [comment]
@davesnx great resource and great idea: "When you look at the top level directory structure, and the source files in the highest level package; do they scream: Health Care System"...

This is why I formed this project, to learn such things.

It should absolutely be within the examples of bullet 1.1, maybe half-sentence in the TL&DR. Can you PR it?

**Comment by BrunoScheufler** [comment]
This is actually a very good article, indeed. I think this is an important point often missed in web development.

**Comment by davesnx** [comment]
I didn't find any case where the frameworks are opinionated where your filesystem must look. A lot of them, suggest a structure for baby steps that usually goes against Screaming Architecture.

**Comment by i0natan** [comment]
@davesnx see your contribution here: https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/breakintcomponents.md

🌻your name is now on the front page :)
