### ISSUE TITLE
Suggestion on testing

### ISSUE THREAD

**Issue by davesnx** [i0natan/nodebestpractices#55]
Hello, 

The section about Testing: `4. Testing And Overall Quality Practices`.

I would explain what's wrong with mocks and when you should only use stubs.
and probably add the **Testing pyramid**, where canaries covers prod and runs like a cron, e2e covers everything but are slow, integration tests and unit tests.

**Comment by i0natan** [comment]
@davesnx thanks for the idea. Can you share some link/paste of a quote that nicely describes the downside of mocks + the *specific testing pyramid that you refer to?

**Comment by davesnx** [comment]
Those are different topics around testing. 

About mocking, I can't explain it in a short amount of time. But I think most of us we experienced before, that mocking a piece is just isolate from the real implementation. You can fall into the temptation to mock everything and you woudn't have a nice test. 

[https://medium.com/javascript-scene/mocking-is-a-code-smell-944a70c90a6a](https://medium.com/javascript-scene/mocking-is-a-code-smell-944a70c90a6a)

---

The idea behind testing pyramid is to have a pyramid with 3 variables: time it takes to run/number of tests/responsability.

Looks something like that: 

![](http://testingblog.manojpahuja.com/wp-content/uploads/2013/12/Testing-Pyramid.jpg.jpeg)

The pyramid is the distribution of the number of tests that your app should have or how to distribute it.

A lot of **unit** that tests the smallest logic and usually are fast.
Have a little less integration that tests the behaviour between components and logic
And even less e2e that tests contracts between services (maybe UI tests, depends on your App)
Finally just a few canaries, the ones that test directly production.

Just for the reference: https://martinfowler.com/bliki/TestPyramid.html

**Comment by snypelife** [comment]
While not explicitly testing related, having an area that explains how to implement dependency injection for things like lib functions and middleware I think would be useful as it would open a nice segue into better stubbing and writing more thorough tests.

**Comment by i0natan** [comment]
@davesnx the testing pyramid seems related to 4.1 as it deals with testing focus. Would you like to PR it?

About avoiding mocks - I'm not sure whether we should provide general testing advice that don't change the way you code Node.JS, or maybe it does?

@snypelife middleware testing is indeed a challenge to write about, Would you like to lead that? what are lib functions?

**Comment by davesnx** [comment]
I will try to get some time to write about testing pyramid, I'm not a native english speaker soooo It would take a little extra time. Thanks.

Instead of creating a topic about avoiding mocks, we could get deep into what kind of tests you can make, what are the patterns or anti-patterns that may appear into your test suit.
