### ISSUE TITLE
3.6 Naming conventions for variables, constants, functions and classes

### ISSUE THREAD

**Issue by syzer** [i0natan/nodebestpractices#72]
```js
// for const name we use UPPERCASE
    const CONFIG = {
      key: 'value'
    };
```
I would like to mention that this is legacy since first versions of fortran.
It didn't have const's! 
So for all registries/variables that we didn't wanna ppl to change we started using UPPERCASE notation.
Again: it was just because language didn't support `const`!

It's not `nice` to see that this legacy lives on 30+ years, even when most major languages/compilers understand `const` word. 

Also most editors understand word `const` and display it different than variables (let, var).

I would postulate to drop 30+ years legacy, and rethink how we are doing things, and change:
```js
// for const name we use UPPERCASE
const CONFIG = {
      key: 'value'
};
```
to
```js
const config = {
   key: 'value'
}
```

**Comment by i0natan** [comment]
Great anecdote. 

I would vote for removing that - a best practice should provide some practical value, it seems pointless in this case. Let's let it park here for few days and see if there are other thoughts. Case not, let's PR it.

**Comment by syzer** [comment]
Also i would change single quoted strings to strings literals:
```js
const config = {
   key: 'value'
}
```
to
```js
const config = {
   key: `value`
}
```
It had a performance impact on old versions of node... but that's not an issue anymore.

**Comment by i0natan** [comment]
@syzer why not PR it? I can do myself if you're busy

**Comment by syzer** [comment]
i will PR it tomorrow

**Comment by refack** [comment]
> It had a performance impact on old versions of node... but that's not an issue anymore.

It may not be noticeable, but it's there. It also implies a different semantic. Do you have any references to preferring only ` over the combination with '?

**Comment by syzer** [comment]
I can replace ` with ' if you want , however:
template literals allow string interpolation

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

When one add two objects: `obj1 + obj2` it works in different way than one might think.
consider this object:
```js
const obj = { valueOf() {return 5}, toString() {return ''} }
```
now: 
```js
typeof (obj + 5) !== typeof `${obj}5`
obj + '42' !== `${obj}42`
```
When ppl see `value`, they expect to have a `string` type, however adding with `+` will leave good attack vector, or and potential instability of system.

So using template literals for strings is a good idea. That's why they were introduced in `es 2015`.

**Comment by BrunoScheufler** [comment]
I would prefer using normal strings by default and template literals only for parts where interpolation is needed. Many style guides also use this pattern, so I think we should really take another look at this change.
