### ISSUE TITLE
Who is this geared for?

### ISSUE THREAD

**Issue by vorpalhex** [i0natan/nodebestpractices#73]
First of all, thanks for compiling this list. However, it's not clear quite who you are targeting since much of this advice is specific to some situation. 

Take for instance 1.1 Structure your solution by components. That makes sense for large enterprise codebases, or codebases with a lot of components that are heavily re-used, but there are also a lot of codebases where that makes no sense (a todo app, a calculator app, a multiplayer game server, etc)

Likewise, the guide gives heavy advice that is Express specific. Express is a great framework for a lot of cases, but probably not larger Enterprise ones. 

It's important to understand that all programming practices have their time and place, and are effectively tradeoffs. Typescript adds in sane consistent types for large codebases, but brings with it severe complexity in small ones. Functional Programming is great for functional problems, but probably isn't a good choice for building an RPG engine in. 

This guide seems to miss this point. Instead of saying "If your situation is this, then a good solution is that", it simply says "Always use Express, a component layout, etc".

**Comment by i0natan** [comment]
Good point @vorpalhex, Let me try.

Writing a practice per scenario signfincantly reduces the simplicity and readability. Instead, I would prefer to define a scope - medium-sized applications and above (=where people struggles most in Node ). That said, I would recommend practicing these principles in almost any app. Many of the tips deal with preventing complexity and handling size. 

Most of the express-related practices are actually valid for any web framework (don't mix layers, etc) so changing express -> web framework (e.g. Express) would make it better?

**Comment by vorpalhex** [comment]
That makes sense, and yes, I think just changing the wording resolves the web framework specificity.
