### ISSUE TITLE
Node isn't single threaded

### ISSUE THREAD

**Issue by vorpalhex** [i0natan/nodebestpractices#74]
This is a common mistake but your guide on point 5.3 says 

> Your poor single thread will keep busy doing networking tasks instead of dealing with your application core and performance will degrade accordingly

While the general advice is good, this is not correct to the Node engine fundamentals. Node uses a single thread for event busing (libuv) but is still running multiple threads in the threadpool for assigning out events. See:

https://www.codingeek.com/tutorials/nodejs/is-nodejs-single-threaded/

https://www.quora.com/Is-Node-js-single-threaded

https://medium.com/@nodejs_recipes/is-nodejs-really-single-threaded-59f1845dfa69

Also note that there's a second part to this advice: You can run high CPU tasks on their own threads away from the event thread (but that's probably non-standard advice since it's much more complex than running such things in the reverse proxy).

**Comment by i0natan** [comment]
@vorpalhex welcome aboard.

To my understanding, and I'd be glad to have @refack take here too, Node is in most of the cases single threaded. Quote: "Today’s operating systems already provide asynchronous interfaces for many I/O tasks (e.g. AIO on Linux). Whenever possible, libuv will use those asynchronous interfaces, avoiding usage of the thread pool"

So practically, the event loop might get blocked from time to time if the user has a busy stack trace (i.e. CPU is the bottleneck). In that case, having more Node processes can speed up.

That said, (1) the current text should probably get clarified (2) not 100% sure that my hypothesis above is correct, @refack would be a bless

**Comment by refack** [comment]
I'll elaborate more later, but the tl;dr is that while node is not "pure" single threaded. All JS code runs in the same thread, so doing CPU bound operations in JS will degrade performance.

**Comment by i0natan** [comment]
@refack u have suggestions on how to re-phrase the text?

**Comment by i0natan** [comment]
PRed a fix here #106 

Note that the advice was to avoid gzipping and other tasks that are CPU intensive. The word networking wasn't meant for libuv/IO tasks rather tasks on the network stream
