### ISSUE TITLE
Modular project structure examples

### ISSUE THREAD

**Issue by RaduCl** [i0natan/nodebestpractices#77]
Regarding project structure in chapters 1.1. and 1.2. , are there any article links or public repos where we could witness such implementations?

**Comment by i0natan** [comment]
I'm not familiar with one besides all my personal projects. It's pretty amazing: almost all Node.JS boilerplate/starters use MVC style partitioning (controllers, models, tests, etc), someday I visited 5 Node.JS forums and pasted two file structure options: MVC style vs components, 99% of the participants voted for the later. And still, there are no examples around.

See our milestones for example project, see also #54. You may also approach me in private so I can share with you an example project

**Comment by duard** [comment]
I prefer to separate the project by functionality => Clients, Products, Orders

**Comment by i0natan** [comment]
@duard do you have an example?

**Comment by i0natan** [comment]
Moved to #69
