### ISSUE TITLE
ESLint info is duplicated

### ISSUE THREAD

**Issue by NameFILIP** [i0natan/nodebestpractices#84]
Two sections mention ESLint with similar text. This is redundant.

**Comment by BrunoScheufler** [comment]
Hi! Would you like to add a PR to remove the wrong/duplicate one?

**Comment by i0natan** [comment]
@BrunoScheufler if you touch, assign to yourself so others know that this issue is in good hands

**Comment by i0natan** [comment]
@BrunoScheufler what is missing to close this ticket?

**Comment by BrunoScheufler** [comment]
The [PR](https://github.com/i0natan/nodebestpractices/pull/89) has to be merged by @idori

**Comment by idori** [comment]
PR merged
