### ISSUE TITLE
Credit section - refer blogs that contributed to this list

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#90]
@refack  @idori @BrunoScheufler 

I suggest adding a section below - 'Credits' with logos of all the companies and blogs which unconsciously contributed ideas. This is not only a fair act but also a great way to (a) communicate that the knowledge here summarizes a lot of sources (b) brand it as de-facto best practices list that aggregates any other

what do you think?

**Comment by BrunoScheufler** [comment]
Sounds like a solid idea! This can also help users to find new blogs and places where Node.js resources are available!

**Comment by refack** [comment]
+1

**Comment by i0natan** [comment]
@idori can u handle this? in overall it probably includes just 10 logos, on your spare time within weeks, is it possible?
