### ISSUE TITLE
Can i translate to korean?

### ISSUE THREAD

**Issue by XoDNr** [i0natan/nodebestpractices#91]
Sorry for miss label. [question]

**Comment by XoDNr** [comment]
Sorry for miss label. **[question]**

**Comment by i0natan** [comment]
@XoDNr that would be our pleasure. Once you do that, you can have your name with bold mentioning on top of the Korean page + added to the core team here.

we already have a procedure for that ([Chinese](https://github.com/i0natan/nodebestpractices/issues/92) and Spanish translations are undergoing), would you like to do that alone or gather few collaborators?

**Comment by XoDNr** [comment]
Thanks! and i do alone !

**Comment by i0natan** [comment]
@XoDNr see #94
