### ISSUE TITLE
Korean translation 행운을 빕니다

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#94]
https://github.com/i0natan/nodebestpractices/blob/korean-translation/README.md

@XoDNr - Korean translation can be officially kicked-off. You're the lead! I'll be at your disposal should you need anything. A branch was created (link below), you should have permissions to it, everyone else must PR before changing anything there.

I would ask/recommend only 2 important guidelines:

Keep the same content & formatting - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and them translate to Korean
Duplicate pages - the content should be translated over a page duplication. Readme.MD became Readme.korean.MD, all other files should be duplicated similarly. So the number of English & Korean pages should be the same. Will create a bold link from the English home page to the Korean home page (with bold credit of course...)

https://github.com/i0natan/nodebestpractices/blob/korean-translation/README.md

**Comment by XoDNr** [comment]
Thank you so much! i'll do my best! Good luck to all you guys, 행운을 빕니다!

**Comment by i0natan** [comment]
Our pleasure to have you here, LMK whether you need anything to push forward.

I suggest pushing a short version (e.g. one bullet), solicit feedback whether all is done right and then proceed

**Comment by i0natan** [comment]
@XoDNr  no rush, just checking whether everything is clear and if I assist in anyway?

**Comment by hinco114** [comment]
@i0natan It looks like doesn't progress... Can I participate in this project?

**Comment by i0natan** [comment]
@hinco114 our pleasure to have you hear, I suggest we first ping @XoDNr and ask for his advice?

**Comment by hinco114** [comment]
@XoDNr 저도 같이 작업을 하고 싶은데 어떻게 참여 할 수 있을까요?

**Comment by hinco114** [comment]
@i0natan I tried to merge Master branch to korean-translate branch for update changes, but this operation cause conflict.
I think you renamed that file name and committed.
By the way, @XoDNr dose not respond, how do I to contribute? Just PR to this branch?
If dose, one solution is I manually merge this conflict.
And the other way is make new branch from current Master branch.

**Comment by i0natan** [comment]
@hinco114 Yes, the way to go is PRing into the Korean branch, not master. Then once it's 100% ready PR the branch into master. Did you finish the entire translation work and want to merge into the master? on which files/branch do are you facing conflicts? I'll be glad to halp in resolving the conflicts

**Comment by i0natan** [comment]
@hinco114 thanks for the update, I'll take a look at the conflict issue soon and share my thoughts. Does it block you now?

**Comment by hinco114** [comment]
Not really, I manually see the difference. But I will do the work faster if that problem is solved.

**Comment by i0natan** [comment]
@hinco114 Fixed the merging issue, kindly pull latest korean-translation. Does it work for you now?

**Comment by hinco114** [comment]
@i0natan I have been busy so reply late. It worked well. I'll PR for the results of my work so far soon. It's not completed version, only translated main important parts.

**Comment by i0natan** [comment]
@hinco114 Sounds great, let's push it one bite at a time.  Maybe as a first version we can translate the home page only and leave the inner pages in English?

**Comment by uronly14me** [comment]
@i0natan Hello, I want to translate it to Korean too.

**Comment by hinco114** [comment]
@uronly14me 안녕하세요, 제가 진행중 여러 일이 겹쳐 진행을 못하고 있었습니다. 같이 진행해도 좋을것 같습니다.

**Comment by uronly14me** [comment]
@hinco114  안녕하세요! #229 에대해 리뷰를 요청합니다.

**Comment by i0natan** [comment]
@uronly14me @hinco114 hmmm, could you translate that for us? 😉

**Comment by songe** [comment]
Not sure who's in charge of reviewing the PRs for Korean translations anymore.
@goldbergyoni  @hinco114  @uronly14me Mind reviewing https://github.com/goldbergyoni/nodebestpractices/pull/651?

**Comment by cisco0808** [comment]
Hello, I want to translate it to Korean.

**Comment by songe** [comment]
Welcome, @cisco0808! You can create a fork, translate pages that remain untranslated, and create a pull request like this one (#665). I currently have a pending PR (#671) that translates sections 1.4-2.1, so you will want to avoid translating those files to avoid duplicated efforts.
