### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by demid5111** [i0natan/nodebestpractices#98]
Hey, I am quite new to this initiative. However eager to participate and translate to Russian. What should I do next?

**Comment by i0natan** [comment]
@demid5111  that would be our pleasure. Once you do that, you can have your name with bold mentioning on top of the Russian page + added to the core team here.

we already have a procedure for that (Chinese and Spanish translations are undergoing), would you like to do that alone or gather few collaborators?

**Comment by demid5111** [comment]
Yes, I will try to complete it till EO January. So, I just fork it or there is some guide how to properly set up my translation repo?

**Comment by i0natan** [comment]
@demid5111 see #105 , good luck :)

**Comment by oshliaer** [comment]
Related #454
